import os
import base64
from datetime import datetime, timezone

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse
from pydantic import BaseModel, Field

from services.openai_service import generate_prompt
from services.templates import TEMPLATE_DESCRIPTIONS, TEMPLATE_LABELS

_INDEX_B64 = (
    "PCFET0NUWVBFIGh0bWw+CjxodG1sIGxhbmc9ImVzIiBjbGFzcz0iZGFyayI+CjxoZWFkPgogICAg"
    "PG1ldGEgY2hhcnNldD0iVVRGLTgiPgogICAgPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9"
    "IndpZHRoPWRldmljZS13aWR0aCwgaW5pdGlhbC1zY2FsZT0xLjAiPgogICAgPHRpdGxlPlpQcm9t"
    "cHQgLSBHZW5lcmFkb3IgZGUgUHJvbXB0cyBwYXJhIERlc2Fycm9sbG8gZGUgU29mdHdhcmU8L3Rp"
    "dGxlPgogICAgPG1ldGEgbmFtZT0iZGVzY3JpcHRpb24iIGNvbnRlbnQ9IkdlbmVyYSBwcm9tcHRz"
    "IGVzdHJ1Y3R1cmFkb3MgcGFyYSBHTE0gb3B0aW1pemFkb3MgcGFyYSBkZXNhcnJvbGxvIGRlIHNv"
    "ZnR3YXJlLiI+CiAgICA8bGluayByZWw9Imljb24iIHR5cGU9ImltYWdlL3gtaWNvbiIgaHJlZj0i"
    "L2Zhdmljb24uaWNvIj4KICAgIDxsaW5rIHJlbD0ic3R5bGVzaGVldCIgaHJlZj0iL2Nzcy9zdHls"
    "ZXMuY3NzIj4KICAgIDxzY3JpcHQgc3JjPSJodHRwczovL3VucGtnLmNvbS9sdWNpZGVAbGF0ZXN0"
    "Ij48L3NjcmlwdD4KPC9oZWFkPgo8Ym9keSBjbGFzcz0ibWluLWgtc2NyZWVuIGJnLWJhY2tncm91"
    "bmQgdGV4dC1mb3JlZ3JvdW5kIGZvbnQtc2FucyBhbnRpYWxpYXNlZCI+CgogICAgPGhlYWRlciBj"
    "bGFzcz0ic3RpY2t5IHRvcC0wIHotNTAgdy1mdWxsIGJvcmRlci1iIGJvcmRlci1ib3JkZXIgYmct"
    "YmFja2dyb3VuZC84MCBiYWNrZHJvcC1ibHVyLXNtIj4KICAgICAgICA8ZGl2IGNsYXNzPSJteC1h"
    "dXRvIGZsZXggaC0xNCBtYXgtdy00eGwgaXRlbXMtY2VudGVyIHB4LTQgc206cHgtNiI+CiAgICAg"
    "ICAgICAgIDxkaXYgY2xhc3M9ImZsZXgtMSI+PC9kaXY+CiAgICAgICAgICAgIDxhIGhyZWY9Ii8i"
    "IGNsYXNzPSJmbGV4IGl0ZW1zLWNlbnRlciBnYXAtMiB0ZXh0LWxnIGZvbnQtc2VtaWJvbGQgdHJh"
    "Y2tpbmctdGlnaHQiPgogICAgICAgICAgICAgICAgPGkgZGF0YS1sdWNpZGU9InphcCIgY2xhc3M9"
    "ImgtNSB3LTUgdGV4dC1wcmltYXJ5Ij48L2k+CiAgICAgICAgICAgICAgICA8c3Bhbj5aUHJvbXB0"
    "PC9zcGFuPgogICAgICAgICAgICA8L2E+CiAgICAgICAgICAgIDxkaXYgY2xhc3M9ImZsZXgtMSBm"
    "bGV4IGl0ZW1zLWNlbnRlciBqdXN0aWZ5LWVuZCBnYXAtMyI+CiAgICAgICAgICAgICAgICA8YnV0"
    "dG9uIGlkPSJ0aGVtZS10b2dnbGUiIGNsYXNzPSJpbmxpbmUtZmxleCBpdGVtcy1jZW50ZXIganVz"
    "dGlmeS1jZW50ZXIgcm91bmRlZC1tZCBib3JkZXIgYm9yZGVyLWJvcmRlciBiZy1iYWNrZ3JvdW5k"
    "IHAtMiB0ZXh0LW11dGVkLWZvcmVncm91bmQgdHJhbnNpdGlvbi1jb2xvcnMgaG92ZXI6YmctYWNj"
    "ZW50IGhvdmVyOnRleHQtYWNjZW50LWZvcmVncm91bmQgY3Vyc29yLXBvaW50ZXIiPgogICAgICAg"
    "ICAgICAgICAgICAgIDxpIGRhdGEtbHVjaWRlPSJzdW4iIGlkPSJ0aGVtZS1pY29uLXN1biIgY2xh"
    "c3M9ImgtNCB3LTQiPjwvaT4KICAgICAgICAgICAgICAgICAgICA8aSBkYXRhLWx1Y2lkZT0ibW9v"
    "biIgaWQ9InRoZW1lLWljb24tbW9vbiIgY2xhc3M9ImgtNCB3LTQgaGlkZGVuIj48L2k+CiAgICAg"
    "ICAgICAgICAgICA8L2J1dHRvbj4KICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgPC9kaXY+CiAg"
    "ICA8L2hlYWRlcj4KCiAgICA8bWFpbiBjbGFzcz0ibXgtYXV0byBtYXgtdy00eGwgcHgtNCBweS04"
    "IHNtOnB4LTYgc206cHktMTIiPgoKICAgICAgICA8c2VjdGlvbiBjbGFzcz0ibWItMTAgdGV4dC1j"
    "ZW50ZXIiPgogICAgICAgICAgICA8aDEgY2xhc3M9InRleHQtM3hsIGZvbnQtYm9sZCB0cmFja2lu"
    "Zy10aWdodCBzbTp0ZXh0LTR4bCI+CiAgICAgICAgICAgICAgICBHZW5lcmEgcHJvbXB0cyBlc3Ry"
    "dWN0dXJhZG9zCiAgICAgICAgICAgICAgICA8c3BhbiBjbGFzcz0idGV4dC1wcmltYXJ5Ij5wYXJh"
    "IEdMTTwvc3Bhbj4KICAgICAgICAgICAgPC9oMT4KICAgICAgICAgICAgPHAgY2xhc3M9Im10LTMg"
    "dGV4dC1tdXRlZC1mb3JlZ3JvdW5kIj4KICAgICAgICAgICAgICAgIERlc2NyaWJlIHR1IHByb3ll"
    "Y3RvIHkgb2J0aWVuZSBwcm9tcHRzIG9wdGltaXphZG9zIHBhcmEgZGVzYXJyb2xsbyBkZSBzb2Z0"
    "d2FyZS4KICAgICAgICAgICAgPC9wPgogICAgICAgIDwvc2VjdGlvbj4KCiAgICAgICAgPHNlY3Rp"
    "b24gY2xhc3M9InNwYWNlLXktNiI+CgogICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAg"
    "PGRpdiBjbGFzcz0iZ3JpZCBncmlkLWNvbHMtNCBnYXAtMiI+CiAgICAgICAgICAgICAgICAgICAg"
    "PGJ1dHRvbiBkYXRhLXR5cGU9InN5c3RlbSIgY2xhc3M9InByb21wdC10eXBlLWNhcmQgZmxleCBp"
    "dGVtcy1jZW50ZXIganVzdGlmeS1jZW50ZXIgZ2FwLTIgcm91bmRlZC1sZyBib3JkZXIgYm9yZGVy"
    "LWJvcmRlciBiZy1jYXJkIHB4LTMgcHktMiB0cmFuc2l0aW9uLWFsbCBob3Zlcjpib3JkZXItcmlu"
    "ZyBob3ZlcjpzaGFkb3ctc20gY3Vyc29yLXBvaW50ZXIiPgogICAgICAgICAgICAgICAgICAgICAg"
    "ICA8aSBkYXRhLWx1Y2lkZT0ibW9uaXRvciIgY2xhc3M9ImgtNCB3LTQiPjwvaT4KICAgICAgICAg"
    "ICAgICAgICAgICAgICAgPHNwYW4gY2xhc3M9InRleHQteHMgZm9udC1tZWRpdW0gdGV4dC1jYXJk"
    "LWZvcmVncm91bmQiPlN5c3RlbTwvc3Bhbj4KICAgICAgICAgICAgICAgICAgICA8L2J1dHRvbj4K"
    "ICAgICAgICAgICAgICAgICAgICA8YnV0dG9uIGRhdGEtdHlwZT0ic3RhcnQiIGNsYXNzPSJwcm9t"
    "cHQtdHlwZS1jYXJkIGZsZXggaXRlbXMtY2VudGVyIGp1c3RpZnktY2VudGVyIGdhcC0yIHJvdW5k"
    "ZWQtbGcgYm9yZGVyIGJvcmRlci1ib3JkZXIgYmctY2FyZCBweC0zIHB5LTIgdHJhbnNpdGlvbi1h"
    "bGwgaG92ZXI6Ym9yZGVyLXJpbmcgaG92ZXI6c2hhZG93LXNtIGN1cnNvci1wb2ludGVyIj4KICAg"
    "ICAgICAgICAgICAgICAgICAgICAgPGkgZGF0YS1sdWNpZGU9InJvY2tldCIgY2xhc3M9ImgtNCB3"
    "LTQiPjwvaT4KICAgICAgICAgICAgICAgICAgICAgICAgPHNwYW4gY2xhc3M9InRleHQteHMgZm9u"
    "dC1tZWRpdW0gdGV4dC1jYXJkLWZvcmVncm91bmQiPlN0YXJ0PC9zcGFuPgogICAgICAgICAgICAg"
    "ICAgICAgIDwvYnV0dG9uPgogICAgICAgICAgICAgICAgICAgIDxidXR0b24gZGF0YS10eXBlPSJm"
    "b2xsb3d1cCIgY2xhc3M9InByb21wdC10eXBlLWNhcmQgZmxleCBpdGVtcy1jZW50ZXIganVzdGlm"
    "eS1jZW50ZXIgZ2FwLTIgcm91bmRlZC1sZyBib3JkZXIgYm9yZGVyLWJvcmRlciBiZy1jYXJkIHB4"
    "LTMgcHktMiB0cmFuc2l0aW9uLWFsbCBob3Zlcjpib3JkZXItcmluZyBob3ZlcjpzaGFkb3ctc20g"
    "Y3Vyc29yLXBvaW50ZXIiPgogICAgICAgICAgICAgICAgICAgICAgICA8aSBkYXRhLWx1Y2lkZT0i"
    "cmVwZWF0IiBjbGFzcz0iaC00IHctNCI+PC9pPgogICAgICAgICAgICAgICAgICAgICAgICA8c3Bh"
    "biBjbGFzcz0idGV4dC14cyBmb250LW1lZGl1bSB0ZXh0LWNhcmQtZm9yZWdyb3VuZCI+Rm9sbG93"
    "LVVwPC9zcGFuPgogICAgICAgICAgICAgICAgICAgIDwvYnV0dG9uPgogICAgICAgICAgICAgICAg"
    "ICAgIDxidXR0b24gZGF0YS10eXBlPSJkZWJ1ZyIgY2xhc3M9InByb21wdC10eXBlLWNhcmQgZmxl"
    "eCBpdGVtcy1jZW50ZXIganVzdGlmeS1jZW50ZXIgZ2FwLTIgcm91bmRlZC1sZyBib3JkZXIgYm9y"
    "ZGVyLWJvcmRlciBiZy1jYXJkIHB4LTMgcHktMiB0cmFuc2l0aW9uLWFsbCBob3Zlcjpib3JkZXIt"
    "cmluZyBob3ZlcjpzaGFkb3ctc20gY3Vyc29yLXBvaW50ZXIiPgogICAgICAgICAgICAgICAgICAg"
    "ICAgICA8aSBkYXRhLWx1Y2lkZT0iYnVnIiBjbGFzcz0iaC00IHctNCI+PC9pPgogICAgICAgICAg"
    "ICAgICAgICAgICAgICA8c3BhbiBjbGFzcz0idGV4dC14cyBmb250LW1lZGl1bSB0ZXh0LWNhcmQt"
    "Zm9yZWdyb3VuZCI+RGVidWc8L3NwYW4+CiAgICAgICAgICAgICAgICAgICAgPC9idXR0b24+CiAg"
    "ICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgPC9kaXY+CgogICAgICAgICAgICA8ZGl2"
    "PgogICAgICAgICAgICAgICAgPGxhYmVsIGZvcj0idXNlci1pbnB1dCIgY2xhc3M9Im1iLTIgYmxv"
    "Y2sgdGV4dC1zbSBmb250LW1lZGl1bSB0ZXh0LWNlbnRlciI+RGVzY3JpYmUgdHUgcHJveWVjdG8g"
    "byB0YXJlYTwvbGFiZWw+CiAgICAgICAgICAgICAgICA8dGV4dGFyZWEKICAgICAgICAgICAgICAg"
    "ICAgICBpZD0idXNlci1pbnB1dCIKICAgICAgICAgICAgICAgICAgICByb3dzPSI0IgogICAgICAg"
    "ICAgICAgICAgICAgIGNsYXNzPSJmbGV4IHctZnVsbCByb3VuZGVkLWxnIGJvcmRlciBib3JkZXIt"
    "aW5wdXQgYmctYmFja2dyb3VuZCBweC0zIHB5LTIuNSB0ZXh0LXNtIHNoYWRvdy14cyB0cmFuc2l0"
    "aW9uLWNvbG9ycyBwbGFjZWhvbGRlcjp0ZXh0LW11dGVkLWZvcmVncm91bmQgZm9jdXMtdmlzaWJs"
    "ZTpvdXRsaW5lLW5vbmUgZm9jdXMtdmlzaWJsZTpyaW5nLTIgZm9jdXMtdmlzaWJsZTpyaW5nLXJp"
    "bmcgcmVzaXplLW5vbmUiCiAgICAgICAgICAgICAgICAgICAgcGxhY2Vob2xkZXI9IkVqZW1wbG86"
    "IENyZWFyIHVuYSBBUEkgUkVTVCBjb24gUHl0aG9uIHkgRmFzdEFQSSBwYXJhIGdlc3Rpb24gZGUg"
    "dGFyZWFzLCBjb24gYXV0ZW50aWNhY2lvbiBKV1QgeSBiYXNlIGRlIGRhdG9zIFBvc3RncmVTUUwu"
    "Li4iCiAgICAgICAgICAgICAgICA+PC90ZXh0YXJlYT4KICAgICAgICAgICAgPC9kaXY+CgogICAg"
    "ICAgICAgICA8ZGl2IGNsYXNzPSJncmlkIGdyaWQtY29scy0xIGdhcC00IHNtOmdyaWQtY29scy0y"
    "Ij4KICAgICAgICAgICAgICAgIDxkaXY+CiAgICAgICAgICAgICAgICAgICAgPGxhYmVsIGZvcj0i"
    "bGFuZ3VhZ2Utc2VsZWN0IiBjbGFzcz0ibWItMiBibG9jayB0ZXh0LXNtIGZvbnQtbWVkaXVtIHRl"
    "eHQtbXV0ZWQtZm9yZWdyb3VuZCI+TGVuZ3VhamUgKG9wY2lvbmFsKTwvbGFiZWw+CiAgICAgICAg"
    "ICAgICAgICAgICAgPHNlbGVjdCBpZD0ibGFuZ3VhZ2Utc2VsZWN0IiBjbGFzcz0iZmxleCBoLTkg"
    "dy1mdWxsIHJvdW5kZWQtbGcgYm9yZGVyIGJvcmRlci1pbnB1dCBiZy1iYWNrZ3JvdW5kIHB4LTMg"
    "dGV4dC1zbSBzaGFkb3cteHMgdHJhbnNpdGlvbi1jb2xvcnMgZm9jdXMtdmlzaWJsZTpvdXRsaW5l"
    "LW5vbmUgZm9jdXMtdmlzaWJsZTpyaW5nLTIgZm9jdXMtdmlzaWJsZTpyaW5nLXJpbmciPgogICAg"
    "ICAgICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVlPSIiPkF1dG8tZGV0ZWN0YXI8L29wdGlv"
    "bj4KICAgICAgICAgICAgICAgICAgICAgICAgPG9wdGlvbiB2YWx1ZT0iUHl0aG9uIj5QeXRob248"
    "L29wdGlvbj4KICAgICAgICAgICAgICAgICAgICAgICAgPG9wdGlvbiB2YWx1ZT0iVHlwZVNjcmlw"
    "dCI+VHlwZVNjcmlwdDwvb3B0aW9uPgogICAgICAgICAgICAgICAgICAgICAgICA8b3B0aW9uIHZh"
    "bHVlPSJEYXJ0Ij5EYXJ0PC9vcHRpb24+CiAgICAgICAgICAgICAgICAgICAgICAgIDxvcHRpb24g"
    "dmFsdWU9IkphdmFTY3JpcHQiPkphdmFTY3JpcHQ8L29wdGlvbj4KICAgICAgICAgICAgICAgICAg"
    "ICAgICAgPG9wdGlvbiB2YWx1ZT0iUnVzdCI+UnVzdDwvb3B0aW9uPgogICAgICAgICAgICAgICAg"
    "ICAgICAgICA8b3B0aW9uIHZhbHVlPSJHbyI+R288L29wdGlvbj4KICAgICAgICAgICAgICAgICAg"
    "ICAgICAgPG9wdGlvbiB2YWx1ZT0iSmF2YSI+SmF2YTwvb3B0aW9uPgogICAgICAgICAgICAgICAg"
    "ICAgICAgICA8b3B0aW9uIHZhbHVlPSJDIyI+QyM8L29wdGlvbj4KICAgICAgICAgICAgICAgICAg"
    "ICAgICAgPG9wdGlvbiB2YWx1ZT0iUEhQIj5QSFA8L29wdGlvbj4KICAgICAgICAgICAgICAgICAg"
    "ICAgICAgPG9wdGlvbiB2YWx1ZT0iUnVieSI+UnVieTwvb3B0aW9uPgogICAgICAgICAgICAgICAg"
    "ICAgICAgICA8b3B0aW9uIHZhbHVlPSJTd2lmdCI+U3dpZnQ8L29wdGlvbj4KICAgICAgICAgICAg"
    "ICAgICAgICAgICAgPG9wdGlvbiB2YWx1ZT0iS290bGluIj5Lb3RsaW48L29wdGlvbj4KICAgICAg"
    "ICAgICAgICAgICAgICA8L3NlbGVjdD4KICAgICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAg"
    "ICAgICAgPGRpdj4KICAgICAgICAgICAgICAgICAgICA8bGFiZWwgZm9yPSJmcmFtZXdvcmstc2Vs"
    "ZWN0IiBjbGFzcz0ibWItMiBibG9jayB0ZXh0LXNtIGZvbnQtbWVkaXVtIHRleHQtbXV0ZWQtZm9y"
    "ZWdyb3VuZCI+RnJhbWV3b3JrIChvcGNpb25hbCk8L2xhYmVsPgogICAgICAgICAgICAgICAgICAg"
    "IDxzZWxlY3QgaWQ9ImZyYW1ld29yay1zZWxlY3QiIGNsYXNzPSJmbGV4IGgtOSB3LWZ1bGwgcm91"
    "bmRlZC1sZyBib3JkZXIgYm9yZGVyLWlucHV0IGJnLWJhY2tncm91bmQgcHgtMyB0ZXh0LXNtIHNo"
    "YWRvdy14cyB0cmFuc2l0aW9uLWNvbG9ycyBmb2N1cy12aXNpYmxlOm91dGxpbmUtbm9uZSBmb2N1"
    "cy12aXNpYmxlOnJpbmctMiBmb2N1cy12aXNpYmxlOnJpbmctcmluZyI+CiAgICAgICAgICAgICAg"
    "ICAgICAgICAgIDxvcHRpb24gdmFsdWU9IiI+TmluZ3VubyAvIEF1dG88L29wdGlvbj4KICAgICAg"
    "ICAgICAgICAgICAgICAgICAgPG9wdGlvbiB2YWx1ZT0iRmFzdEFQSSI+RmFzdEFQSTwvb3B0aW9u"
    "PgogICAgICAgICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVlPSJEamFuZ28iPkRqYW5nbzwv"
    "b3B0aW9uPgogICAgICAgICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVlPSJGbHV0dGVyIj5G"
    "bHV0dGVyPC9vcHRpb24+CiAgICAgICAgICAgICAgICAgICAgICAgIDxvcHRpb24gdmFsdWU9IkZs"
    "YXNrIj5GbGFzazwvb3B0aW9uPgogICAgICAgICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVl"
    "PSJOZXh0LmpzIj5OZXh0LmpzPC9vcHRpb24+CiAgICAgICAgICAgICAgICAgICAgICAgIDxvcHRp"
    "b24gdmFsdWU9IlJlYWN0Ij5SZWFjdDwvb3B0aW9uPgogICAgICAgICAgICAgICAgICAgICAgICA8"
    "b3B0aW9uIHZhbHVlPSJWdWUuanMiPlZ1ZS5qczwvb3B0aW9uPgogICAgICAgICAgICAgICAgICAg"
    "ICAgICA8b3B0aW9uIHZhbHVlPSJFeHByZXNzIj5FeHByZXNzPC9vcHRpb24+CiAgICAgICAgICAg"
    "ICAgICAgICAgICAgIDxvcHRpb24gdmFsdWU9Ik5lc3RKUyI+TmVzdEpTPC9vcHRpb24+CiAgICAg"
    "ICAgICAgICAgICAgICAgICAgIDxvcHRpb24gdmFsdWU9IlNwcmluZyBCb290Ij5TcHJpbmcgQm9v"
    "dDwvb3B0aW9uPgogICAgICAgICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVlPSJBY3RpeCI+"
    "QWN0aXg8L29wdGlvbj4KICAgICAgICAgICAgICAgICAgICAgICAgPG9wdGlvbiB2YWx1ZT0iQXh1"
    "bSI+QXh1bTwvb3B0aW9uPgogICAgICAgICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVlPSJM"
    "YXJhdmVsIj5MYXJhdmVsPC9vcHRpb24+CiAgICAgICAgICAgICAgICAgICAgICAgIDxvcHRpb24g"
    "dmFsdWU9IlJhaWxzIj5SYWlsczwvb3B0aW9uPgogICAgICAgICAgICAgICAgICAgIDwvc2VsZWN0"
    "PgogICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgIDwvZGl2PgoKICAgICAgICAgICAg"
    "PGJ1dHRvbgogICAgICAgICAgICAgICAgaWQ9ImdlbmVyYXRlLWJ0biIKICAgICAgICAgICAgICAg"
    "IGNsYXNzPSJpbmxpbmUtZmxleCB3LWZ1bGwgaXRlbXMtY2VudGVyIGp1c3RpZnktY2VudGVyIGdh"
    "cC0yIHJvdW5kZWQtbGcgYmctcHJpbWFyeSBweC00IHB5LTIuNSB0ZXh0LXNtIGZvbnQtbWVkaXVt"
    "IHRleHQtcHJpbWFyeS1mb3JlZ3JvdW5kIHNoYWRvdy14cyB0cmFuc2l0aW9uLWNvbG9ycyBob3Zl"
    "cjpiZy1wcmltYXJ5LzkwIGRpc2FibGVkOnBvaW50ZXItZXZlbnRzLW5vbmUgZGlzYWJsZWQ6b3Bh"
    "Y2l0eS01MCBjdXJzb3ItcG9pbnRlciIKICAgICAgICAgICAgICAgIGRpc2FibGVkCiAgICAgICAg"
    "ICAgID4KICAgICAgICAgICAgICAgIDxpIGRhdGEtbHVjaWRlPSJ6YXAiIGNsYXNzPSJoLTQgdy00"
    "Ij48L2k+CiAgICAgICAgICAgICAgICA8c3BhbiBpZD0iYnRuLXRleHQiPkdlbmVyYXIgUHJvbXB0"
    "PC9zcGFuPgogICAgICAgICAgICAgICAgPHNwYW4gaWQ9ImJ0bi1zcGlubmVyIiBjbGFzcz0iaGlk"
    "ZGVuIj4KICAgICAgICAgICAgICAgICAgICA8c3ZnIGNsYXNzPSJoLTQgdy00IGFuaW1hdGUtc3Bp"
    "biIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIj48Y2lyY2xlIGNsYXNzPSJvcGFjaXR5"
    "LTI1IiBjeD0iMTIiIGN5PSIxMiIgcj0iMTAiIHN0cm9rZT0iY3VycmVudENvbG9yIiBzdHJva2Ut"
    "d2lkdGg9IjQiPjwvY2lyY2xlPjxwYXRoIGNsYXNzPSJvcGFjaXR5LTc1IiBmaWxsPSJjdXJyZW50"
    "Q29sb3IiIGQ9Ik00IDEyYTggOCAwIDAxOC04VjBDNS4zNzMgMCAwIDUuMzczIDAgMTJoNHoiPjwv"
    "cGF0aD48L3N2Zz4KICAgICAgICAgICAgICAgIDwvc3Bhbj4KICAgICAgICAgICAgPC9idXR0b24+"
    "CgogICAgICAgIDwvc2VjdGlvbj4KCiAgICAgICAgPHNlY3Rpb24gaWQ9ImVycm9yLXNlY3Rpb24i"
    "IGNsYXNzPSJtdC02IGhpZGRlbiI+CiAgICAgICAgICAgIDxkaXYgY2xhc3M9InJvdW5kZWQtbGcg"
    "Ym9yZGVyIGJvcmRlci1kZXN0cnVjdGl2ZS81MCBiZy1kZXN0cnVjdGl2ZS8xMCBwLTQgdGV4dC1z"
    "bSB0ZXh0LWRlc3RydWN0aXZlIj4KICAgICAgICAgICAgICAgIDxwIGlkPSJlcnJvci1tZXNzYWdl"
    "Ij48L3A+CiAgICAgICAgICAgIDwvZGl2PgogICAgICAgIDwvc2VjdGlvbj4KCiAgICAgICAgPHNl"
    "Y3Rpb24gaWQ9InJlc3VsdC1zZWN0aW9uIiBjbGFzcz0ibXQtOCBoaWRkZW4iPgogICAgICAgICAg"
    "ICA8ZGl2IGNsYXNzPSJyb3VuZGVkLWxnIGJvcmRlciBib3JkZXItYm9yZGVyIGJnLWNhcmQgc2hh"
    "ZG93LXNtIj4KICAgICAgICAgICAgICAgIDxkaXYgY2xhc3M9ImZsZXggaXRlbXMtY2VudGVyIGp1"
    "c3RpZnktYmV0d2VlbiBib3JkZXItYiBib3JkZXItYm9yZGVyIHB4LTQgcHktMyI+CiAgICAgICAg"
    "ICAgICAgICAgICAgPGRpdiBjbGFzcz0iZmxleCBpdGVtcy1jZW50ZXIgZ2FwLTIiPgogICAgICAg"
    "ICAgICAgICAgICAgICAgICA8c3BhbiBpZD0icmVzdWx0LWljb24iPjwvc3Bhbj4KICAgICAgICAg"
    "ICAgICAgICAgICAgICAgPGgyIGlkPSJyZXN1bHQtdGl0bGUiIGNsYXNzPSJ0ZXh0LXNtIGZvbnQt"
    "c2VtaWJvbGQgdGV4dC1jYXJkLWZvcmVncm91bmQiPjwvaDI+CiAgICAgICAgICAgICAgICAgICAg"
    "PC9kaXY+CiAgICAgICAgICAgICAgICAgICAgPGRpdiBjbGFzcz0iZmxleCBpdGVtcy1jZW50ZXIg"
    "Z2FwLTIiPgogICAgICAgICAgICAgICAgICAgICAgICA8YnV0dG9uIGlkPSJjb3B5LWJ0biIgY2xh"
    "c3M9ImlubGluZS1mbGV4IGl0ZW1zLWNlbnRlciBnYXAtMS41IHJvdW5kZWQtbWQgYm9yZGVyIGJv"
    "cmRlci1ib3JkZXIgYmctYmFja2dyb3VuZCBweC0yLjUgcHktMS41IHRleHQteHMgZm9udC1tZWRp"
    "dW0gdGV4dC1tdXRlZC1mb3JlZ3JvdW5kIHRyYW5zaXRpb24tY29sb3JzIGhvdmVyOmJnLWFjY2Vu"
    "dCBob3Zlcjp0ZXh0LWFjY2VudC1mb3JlZ3JvdW5kIGN1cnNvci1wb2ludGVyIj4KICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgIDxpIGRhdGEtbHVjaWRlPSJjb3B5IiBjbGFzcz0iaC0zLjUgdy0z"
    "LjUiPjwvaT4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIENvcGlhcgogICAgICAgICAgICAg"
    "ICAgICAgICAgICA8L2J1dHRvbj4KICAgICAgICAgICAgICAgICAgICAgICAgPGJ1dHRvbiBpZD0i"
    "cmVnZW5lcmF0ZS1idG4iIGNsYXNzPSJpbmxpbmUtZmxleCBpdGVtcy1jZW50ZXIgZ2FwLTEuNSBy"
    "b3VuZGVkLW1kIGJvcmRlciBib3JkZXItYm9yZGVyIGJnLWJhY2tncm91bmQgcHgtMi41IHB5LTEu"
    "NSB0ZXh0LXhzIGZvbnQtbWVkaXVtIHRleHQtbXV0ZWQtZm9yZWdyb3VuZCB0cmFuc2l0aW9uLWNv"
    "bG9ycyBob3ZlcjpiZy1hY2NlbnQgaG92ZXI6dGV4dC1hY2NlbnQtZm9yZWdyb3VuZCBjdXJzb3It"
    "cG9pbnRlciI+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8aSBkYXRhLWx1Y2lkZT0icmVm"
    "cmVzaC1jdyIgY2xhc3M9ImgtMy41IHctMy41Ij48L2k+CiAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICBSZWdlbmVyYXIKICAgICAgICAgICAgICAgICAgICAgICAgPC9idXR0b24+CiAgICAgICAg"
    "ICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgICAg"
    "IDxkaXYgY2xhc3M9InAtNCI+CiAgICAgICAgICAgICAgICAgICAgPHByZSBpZD0icmVzdWx0LWNv"
    "bnRlbnQiIGNsYXNzPSJ3aGl0ZXNwYWNlLXByZS13cmFwIGJyZWFrLXdvcmRzIGZvbnQtbW9ubyB0"
    "ZXh0LXNtIGxlYWRpbmctcmVsYXhlZCB0ZXh0LWNhcmQtZm9yZWdyb3VuZCI+PC9wcmU+CiAgICAg"
    "ICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgICAgIDxkaXYgY2xhc3M9ImJvcmRlci10IGJv"
    "cmRlci1ib3JkZXIgcHgtNCBweS0yIj4KICAgICAgICAgICAgICAgICAgICA8cCBpZD0icmVzdWx0"
    "LXRpbWVzdGFtcCIgY2xhc3M9InRleHQteHMgdGV4dC1tdXRlZC1mb3JlZ3JvdW5kIj48L3A+CiAg"
    "ICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgPC9zZWN0aW9u"
    "PgoKICAgIDwvbWFpbj4KCiAgICA8Zm9vdGVyIGNsYXNzPSJib3JkZXItdCBib3JkZXItYm9yZGVy"
    "IHB5LTYgdGV4dC1jZW50ZXIgdGV4dC14cyB0ZXh0LW11dGVkLWZvcmVncm91bmQiPgogICAgICAg"
    "IDxwPlpQcm9tcHQgJm1kYXNoOyBHZW5lcmFkb3IgZGUgcHJvbXB0cyBlc3RydWN0dXJhZG9zIHBh"
    "cmEgR0xNPC9wPgogICAgPC9mb290ZXI+CgogICAgPHNjcmlwdCBzcmM9Ii9qcy9hcHAuanMiPjwv"
    "c2NyaXB0Pgo8L2JvZHk+CjwvaHRtbD4K"
)



INDEX_HTML = base64.b64decode(_INDEX_B64).decode("utf-8")

load_dotenv()

app = FastAPI(
    title="ZPrompt",
    description="Generador de prompts estructurados para desarrollo de software",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


class PromptRequest(BaseModel):
    text: str = Field(..., min_length=5, max_length=5000)
    prompt_type: str = Field(..., pattern="^(system|start|followup|debug)$")
    language: str | None = None
    framework: str | None = None


class PromptResponse(BaseModel):
    prompt: str
    prompt_type: str
    label: str
    timestamp: str


@app.get("/")
def serve_index():
    return HTMLResponse(content=INDEX_HTML)


@app.get("/api/health")
def health_check():
    return {"status": "ok", "timestamp": datetime.now(timezone.utc).isoformat()}


@app.get("/api/templates")
def get_templates():
    result = []
    for key, label in TEMPLATE_LABELS.items():
        result.append(
            {
                "id": key,
                "label": label,
                "description": TEMPLATE_DESCRIPTIONS.get(key, ""),
            }
        )
    return {"templates": result}


@app.post("/api/generate", response_model=PromptResponse)
async def create_prompt(request: PromptRequest):
    if not os.environ.get("OPENAI_API_KEY"):
        raise HTTPException(
            status_code=500,
            detail="OPENAI_API_KEY no configurada. Agregala como variable de entorno.",
        )

    try:
        prompt_text = await generate_prompt(
            text=request.text,
            prompt_type=request.prompt_type,
            language=request.language,
            framework=request.framework,
        )
        return PromptResponse(
            prompt=prompt_text,
            prompt_type=request.prompt_type,
            label=TEMPLATE_LABELS.get(request.prompt_type, ""),
            timestamp=datetime.now(timezone.utc).isoformat(),
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        raise HTTPException(
            status_code=500, detail=f"Error generando prompt: {str(e)}"
        )


@app.get("/api/data")
def get_sample_data():
    return {
        "data": [
            {"id": 1, "name": "Sample Item 1", "value": 100},
            {"id": 2, "name": "Sample Item 2", "value": 200},
            {"id": 3, "name": "Sample Item 3", "value": 300},
        ],
        "total": 3,
        "timestamp": "2024-01-01T00:00:00Z",
    }

_INDEX_B64 = (
    "PCFET0NUWVBFIGh0bWw+CjxodG1sIGxhbmc9ImVzIiBjbGFzcz0iZGFyayI+CjxoZWFkPgogICAg"
    "PG1ldGEgY2hhcnNldD0iVVRGLTgiPgogICAgPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9"
    "IndpZHRoPWRldmljZS13aWR0aCwgaW5pdGlhbC1zY2FsZT0xLjAiPgogICAgPHRpdGxlPlpQcm9t"
    "cHQgLSBHZW5lcmFkb3IgZGUgUHJvbXB0cyBwYXJhIERlc2Fycm9sbG8gZGUgU29mdHdhcmU8L3Rp"
    "dGxlPgogICAgPG1ldGEgbmFtZT0iZGVzY3JpcHRpb24iIGNvbnRlbnQ9IkdlbmVyYSBwcm9tcHRz"
    "IGVzdHJ1Y3R1cmFkb3MgcGFyYSBHTE0gb3B0aW1pemFkb3MgcGFyYSBkZXNhcnJvbGxvIGRlIHNv"
    "ZnR3YXJlLiI+CiAgICA8bGluayByZWw9Imljb24iIHR5cGU9ImltYWdlL3gtaWNvbiIgaHJlZj0i"
    "L2Zhdmljb24uaWNvIj4KICAgIDxsaW5rIHJlbD0ic3R5bGVzaGVldCIgaHJlZj0iL2Nzcy9zdHls"
    "ZXMuY3NzIj4KICAgIDxzY3JpcHQgc3JjPSJodHRwczovL3VucGtnLmNvbS9sdWNpZGVAbGF0ZXN0"
    "Ij48L3NjcmlwdD4KPC9oZWFkPgo8Ym9keSBjbGFzcz0ibWluLWgtc2NyZWVuIGJnLWJhY2tncm91"
    "bmQgdGV4dC1mb3JlZ3JvdW5kIGZvbnQtc2FucyBhbnRpYWxpYXNlZCI+CgogICAgPGhlYWRlciBj"
    "bGFzcz0ic3RpY2t5IHRvcC0wIHotNTAgdy1mdWxsIGJvcmRlci1iIGJvcmRlci1ib3JkZXIgYmct"
    "YmFja2dyb3VuZC84MCBiYWNrZHJvcC1ibHVyLXNtIj4KICAgICAgICA8ZGl2IGNsYXNzPSJteC1h"
    "dXRvIGZsZXggaC0xNCBtYXgtdy00eGwgaXRlbXMtY2VudGVyIHB4LTQgc206cHgtNiI+CiAgICAg"
    "ICAgICAgIDxkaXYgY2xhc3M9ImZsZXgtMSI+PC9kaXY+CiAgICAgICAgICAgIDxhIGhyZWY9Ii8i"
    "IGNsYXNzPSJmbGV4IGl0ZW1zLWNlbnRlciBnYXAtMiB0ZXh0LWxnIGZvbnQtc2VtaWJvbGQgdHJh"
    "Y2tpbmctdGlnaHQiPgogICAgICAgICAgICAgICAgPGkgZGF0YS1sdWNpZGU9InphcCIgY2xhc3M9"
    "ImgtNSB3LTUgdGV4dC1wcmltYXJ5Ij48L2k+CiAgICAgICAgICAgICAgICA8c3Bhbj5aUHJvbXB0"
    "PC9zcGFuPgogICAgICAgICAgICA8L2E+CiAgICAgICAgICAgIDxkaXYgY2xhc3M9ImZsZXgtMSBm"
    "bGV4IGl0ZW1zLWNlbnRlciBqdXN0aWZ5LWVuZCBnYXAtMyI+CiAgICAgICAgICAgICAgICA8YnV0"
    "dG9uIGlkPSJ0aGVtZS10b2dnbGUiIGNsYXNzPSJpbmxpbmUtZmxleCBpdGVtcy1jZW50ZXIganVz"
    "dGlmeS1jZW50ZXIgcm91bmRlZC1tZCBib3JkZXIgYm9yZGVyLWJvcmRlciBiZy1iYWNrZ3JvdW5k"
    "IHAtMiB0ZXh0LW11dGVkLWZvcmVncm91bmQgdHJhbnNpdGlvbi1jb2xvcnMgaG92ZXI6YmctYWNj"
    "ZW50IGhvdmVyOnRleHQtYWNjZW50LWZvcmVncm91bmQgY3Vyc29yLXBvaW50ZXIiPgogICAgICAg"
    "ICAgICAgICAgICAgIDxpIGRhdGEtbHVjaWRlPSJzdW4iIGlkPSJ0aGVtZS1pY29uLXN1biIgY2xh"
    "c3M9ImgtNCB3LTQiPjwvaT4KICAgICAgICAgICAgICAgICAgICA8aSBkYXRhLWx1Y2lkZT0ibW9v"
    "biIgaWQ9InRoZW1lLWljb24tbW9vbiIgY2xhc3M9ImgtNCB3LTQgaGlkZGVuIj48L2k+CiAgICAg"
    "ICAgICAgICAgICA8L2J1dHRvbj4KICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgPC9kaXY+CiAg"
    "ICA8L2hlYWRlcj4KCiAgICA8bWFpbiBjbGFzcz0ibXgtYXV0byBtYXgtdy00eGwgcHgtNCBweS04"
    "IHNtOnB4LTYgc206cHktMTIiPgoKICAgICAgICA8c2VjdGlvbiBjbGFzcz0ibWItMTAgdGV4dC1j"
    "ZW50ZXIiPgogICAgICAgICAgICA8aDEgY2xhc3M9InRleHQtM3hsIGZvbnQtYm9sZCB0cmFja2lu"
    "Zy10aWdodCBzbTp0ZXh0LTR4bCI+CiAgICAgICAgICAgICAgICBHZW5lcmEgcHJvbXB0cyBlc3Ry"
    "dWN0dXJhZG9zCiAgICAgICAgICAgICAgICA8c3BhbiBjbGFzcz0idGV4dC1wcmltYXJ5Ij5wYXJh"
    "IEdMTTwvc3Bhbj4KICAgICAgICAgICAgPC9oMT4KICAgICAgICAgICAgPHAgY2xhc3M9Im10LTMg"
    "dGV4dC1tdXRlZC1mb3JlZ3JvdW5kIj4KICAgICAgICAgICAgICAgIERlc2NyaWJlIHR1IHByb3ll"
    "Y3RvIHkgb2J0aWVuZSBwcm9tcHRzIG9wdGltaXphZG9zIHBhcmEgZGVzYXJyb2xsbyBkZSBzb2Z0"
    "d2FyZS4KICAgICAgICAgICAgPC9wPgogICAgICAgIDwvc2VjdGlvbj4KCiAgICAgICAgPHNlY3Rp"
    "b24gY2xhc3M9InNwYWNlLXktNiI+CgogICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAg"
    "PGRpdiBjbGFzcz0iZ3JpZCBncmlkLWNvbHMtNCBnYXAtMiI+CiAgICAgICAgICAgICAgICAgICAg"
    "PGJ1dHRvbiBkYXRhLXR5cGU9InN5c3RlbSIgY2xhc3M9InByb21wdC10eXBlLWNhcmQgZmxleCBp"
    "dGVtcy1jZW50ZXIganVzdGlmeS1jZW50ZXIgZ2FwLTIgcm91bmRlZC1sZyBib3JkZXIgYm9yZGVy"
    "LWJvcmRlciBiZy1jYXJkIHB4LTMgcHktMiB0cmFuc2l0aW9uLWFsbCBob3Zlcjpib3JkZXItcmlu"
    "ZyBob3ZlcjpzaGFkb3ctc20gY3Vyc29yLXBvaW50ZXIiPgogICAgICAgICAgICAgICAgICAgICAg"
    "ICA8aSBkYXRhLWx1Y2lkZT0ibW9uaXRvciIgY2xhc3M9ImgtNCB3LTQiPjwvaT4KICAgICAgICAg"
    "ICAgICAgICAgICAgICAgPHNwYW4gY2xhc3M9InRleHQteHMgZm9udC1tZWRpdW0gdGV4dC1jYXJk"
    "LWZvcmVncm91bmQiPlN5c3RlbTwvc3Bhbj4KICAgICAgICAgICAgICAgICAgICA8L2J1dHRvbj4K"
    "ICAgICAgICAgICAgICAgICAgICA8YnV0dG9uIGRhdGEtdHlwZT0ic3RhcnQiIGNsYXNzPSJwcm9t"
    "cHQtdHlwZS1jYXJkIGZsZXggaXRlbXMtY2VudGVyIGp1c3RpZnktY2VudGVyIGdhcC0yIHJvdW5k"
    "ZWQtbGcgYm9yZGVyIGJvcmRlci1ib3JkZXIgYmctY2FyZCBweC0zIHB5LTIgdHJhbnNpdGlvbi1h"
    "bGwgaG92ZXI6Ym9yZGVyLXJpbmcgaG92ZXI6c2hhZG93LXNtIGN1cnNvci1wb2ludGVyIj4KICAg"
    "ICAgICAgICAgICAgICAgICAgICAgPGkgZGF0YS1sdWNpZGU9InJvY2tldCIgY2xhc3M9ImgtNCB3"
    "LTQiPjwvaT4KICAgICAgICAgICAgICAgICAgICAgICAgPHNwYW4gY2xhc3M9InRleHQteHMgZm9u"
    "dC1tZWRpdW0gdGV4dC1jYXJkLWZvcmVncm91bmQiPlN0YXJ0PC9zcGFuPgogICAgICAgICAgICAg"
    "ICAgICAgIDwvYnV0dG9uPgogICAgICAgICAgICAgICAgICAgIDxidXR0b24gZGF0YS10eXBlPSJm"
    "b2xsb3d1cCIgY2xhc3M9InByb21wdC10eXBlLWNhcmQgZmxleCBpdGVtcy1jZW50ZXIganVzdGlm"
    "eS1jZW50ZXIgZ2FwLTIgcm91bmRlZC1sZyBib3JkZXIgYm9yZGVyLWJvcmRlciBiZy1jYXJkIHB4"
    "LTMgcHktMiB0cmFuc2l0aW9uLWFsbCBob3Zlcjpib3JkZXItcmluZyBob3ZlcjpzaGFkb3ctc20g"
    "Y3Vyc29yLXBvaW50ZXIiPgogICAgICAgICAgICAgICAgICAgICAgICA8aSBkYXRhLWx1Y2lkZT0i"
    "cmVwZWF0IiBjbGFzcz0iaC00IHctNCI+PC9pPgogICAgICAgICAgICAgICAgICAgICAgICA8c3Bh"
    "biBjbGFzcz0idGV4dC14cyBmb250LW1lZGl1bSB0ZXh0LWNhcmQtZm9yZWdyb3VuZCI+Rm9sbG93"
    "LVVwPC9zcGFuPgogICAgICAgICAgICAgICAgICAgIDwvYnV0dG9uPgogICAgICAgICAgICAgICAg"
    "ICAgIDxidXR0b24gZGF0YS10eXBlPSJkZWJ1ZyIgY2xhc3M9InByb21wdC10eXBlLWNhcmQgZmxl"
    "eCBpdGVtcy1jZW50ZXIganVzdGlmeS1jZW50ZXIgZ2FwLTIgcm91bmRlZC1sZyBib3JkZXIgYm9y"
    "ZGVyLWJvcmRlciBiZy1jYXJkIHB4LTMgcHktMiB0cmFuc2l0aW9uLWFsbCBob3Zlcjpib3JkZXIt"
    "cmluZyBob3ZlcjpzaGFkb3ctc20gY3Vyc29yLXBvaW50ZXIiPgogICAgICAgICAgICAgICAgICAg"
    "ICAgICA8aSBkYXRhLWx1Y2lkZT0iYnVnIiBjbGFzcz0iaC00IHctNCI+PC9pPgogICAgICAgICAg"
    "ICAgICAgICAgICAgICA8c3BhbiBjbGFzcz0idGV4dC14cyBmb250LW1lZGl1bSB0ZXh0LWNhcmQt"
    "Zm9yZWdyb3VuZCI+RGVidWc8L3NwYW4+CiAgICAgICAgICAgICAgICAgICAgPC9idXR0b24+CiAg"
    "ICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgPC9kaXY+CgogICAgICAgICAgICA8ZGl2"
    "PgogICAgICAgICAgICAgICAgPGxhYmVsIGZvcj0idXNlci1pbnB1dCIgY2xhc3M9Im1iLTIgYmxv"
    "Y2sgdGV4dC1zbSBmb250LW1lZGl1bSB0ZXh0LWNlbnRlciI+RGVzY3JpYmUgdHUgcHJveWVjdG8g"
    "byB0YXJlYTwvbGFiZWw+CiAgICAgICAgICAgICAgICA8dGV4dGFyZWEKICAgICAgICAgICAgICAg"
    "ICAgICBpZD0idXNlci1pbnB1dCIKICAgICAgICAgICAgICAgICAgICByb3dzPSI0IgogICAgICAg"
    "ICAgICAgICAgICAgIGNsYXNzPSJmbGV4IHctZnVsbCByb3VuZGVkLWxnIGJvcmRlciBib3JkZXIt"
    "aW5wdXQgYmctYmFja2dyb3VuZCBweC0zIHB5LTIuNSB0ZXh0LXNtIHNoYWRvdy14cyB0cmFuc2l0"
    "aW9uLWNvbG9ycyBwbGFjZWhvbGRlcjp0ZXh0LW11dGVkLWZvcmVncm91bmQgZm9jdXMtdmlzaWJs"
    "ZTpvdXRsaW5lLW5vbmUgZm9jdXMtdmlzaWJsZTpyaW5nLTIgZm9jdXMtdmlzaWJsZTpyaW5nLXJp"
    "bmcgcmVzaXplLW5vbmUiCiAgICAgICAgICAgICAgICAgICAgcGxhY2Vob2xkZXI9IkVqZW1wbG86"
    "IENyZWFyIHVuYSBBUEkgUkVTVCBjb24gUHl0aG9uIHkgRmFzdEFQSSBwYXJhIGdlc3Rpb24gZGUg"
    "dGFyZWFzLCBjb24gYXV0ZW50aWNhY2lvbiBKV1QgeSBiYXNlIGRlIGRhdG9zIFBvc3RncmVTUUwu"
    "Li4iCiAgICAgICAgICAgICAgICA+PC90ZXh0YXJlYT4KICAgICAgICAgICAgPC9kaXY+CgogICAg"
    "ICAgICAgICA8ZGl2IGNsYXNzPSJncmlkIGdyaWQtY29scy0xIGdhcC00IHNtOmdyaWQtY29scy0y"
    "Ij4KICAgICAgICAgICAgICAgIDxkaXY+CiAgICAgICAgICAgICAgICAgICAgPGxhYmVsIGZvcj0i"
    "bGFuZ3VhZ2Utc2VsZWN0IiBjbGFzcz0ibWItMiBibG9jayB0ZXh0LXNtIGZvbnQtbWVkaXVtIHRl"
    "eHQtbXV0ZWQtZm9yZWdyb3VuZCI+TGVuZ3VhamUgKG9wY2lvbmFsKTwvbGFiZWw+CiAgICAgICAg"
    "ICAgICAgICAgICAgPHNlbGVjdCBpZD0ibGFuZ3VhZ2Utc2VsZWN0IiBjbGFzcz0iZmxleCBoLTkg"
    "dy1mdWxsIHJvdW5kZWQtbGcgYm9yZGVyIGJvcmRlci1pbnB1dCBiZy1iYWNrZ3JvdW5kIHB4LTMg"
    "dGV4dC1zbSBzaGFkb3cteHMgdHJhbnNpdGlvbi1jb2xvcnMgZm9jdXMtdmlzaWJsZTpvdXRsaW5l"
    "LW5vbmUgZm9jdXMtdmlzaWJsZTpyaW5nLTIgZm9jdXMtdmlzaWJsZTpyaW5nLXJpbmciPgogICAg"
    "ICAgICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVlPSIiPkF1dG8tZGV0ZWN0YXI8L29wdGlv"
    "bj4KICAgICAgICAgICAgICAgICAgICAgICAgPG9wdGlvbiB2YWx1ZT0iUHl0aG9uIj5QeXRob248"
    "L29wdGlvbj4KICAgICAgICAgICAgICAgICAgICAgICAgPG9wdGlvbiB2YWx1ZT0iVHlwZVNjcmlw"
_INDEX_B64 = (
    "PCFET0NUWVBFIGh0bWw+CjxodG1sIGxhbmc9ImVzIiBjbGFzcz0iZGFyayI+CjxoZWFkPgogICAg"
    "PG1ldGEgY2hhcnNldD0iVVRGLTgiPgogICAgPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9"
    "IndpZHRoPWRldmljZS13aWR0aCwgaW5pdGlhbC1zY2FsZT0xLjAiPgogICAgPHRpdGxlPlpQcm9t"
    "cHQgLSBHZW5lcmFkb3IgZGUgUHJvbXB0cyBwYXJhIERlc2Fycm9sbG8gZGUgU29mdHdhcmU8L3Rp"
    "dGxlPgogICAgPG1ldGEgbmFtZT0iZGVzY3JpcHRpb24iIGNvbnRlbnQ9IkdlbmVyYSBwcm9tcHRz"
    "IGVzdHJ1Y3R1cmFkb3MgcGFyYSBHTE0gb3B0aW1pemFkb3MgcGFyYSBkZXNhcnJvbGxvIGRlIHNv"
    "ZnR3YXJlLiI+CiAgICA8bGluayByZWw9Imljb24iIHR5cGU9ImltYWdlL3gtaWNvbiIgaHJlZj0i"
    "L2Zhdmljb24uaWNvIj4KICAgIDxsaW5rIHJlbD0ic3R5bGVzaGVldCIgaHJlZj0iL2Nzcy9zdHls"
    "ZXMuY3NzIj4KICAgIDxzY3JpcHQgc3JjPSJodHRwczovL3VucGtnLmNvbS9sdWNpZGVAbGF0ZXN0"
    "Ij48L3NjcmlwdD4KPC9oZWFkPgo8Ym9keSBjbGFzcz0ibWluLWgtc2NyZWVuIGJnLWJhY2tncm91"
    "bmQgdGV4dC1mb3JlZ3JvdW5kIGZvbnQtc2FucyBhbnRpYWxpYXNlZCI+CgogICAgPGhlYWRlciBj"
    "bGFzcz0ic3RpY2t5IHRvcC0wIHotNTAgdy1mdWxsIGJvcmRlci1iIGJvcmRlci1ib3JkZXIgYmct"
    "YmFja2dyb3VuZC84MCBiYWNrZHJvcC1ibHVyLXNtIj4KICAgICAgICA8ZGl2IGNsYXNzPSJteC1h"
    "dXRvIGZsZXggaC0xNCBtYXgtdy00eGwgaXRlbXMtY2VudGVyIHB4LTQgc206cHgtNiI+CiAgICAg"
    "ICAgICAgIDxkaXYgY2xhc3M9ImZsZXgtMSI+PC9kaXY+CiAgICAgICAgICAgIDxhIGhyZWY9Ii8i"
    "IGNsYXNzPSJmbGV4IGl0ZW1zLWNlbnRlciBnYXAtMiB0ZXh0LWxnIGZvbnQtc2VtaWJvbGQgdHJh"
    "Y2tpbmctdGlnaHQiPgogICAgICAgICAgICAgICAgPGkgZGF0YS1sdWNpZGU9InphcCIgY2xhc3M9"
    "ImgtNSB3LTUgdGV4dC1wcmltYXJ5Ij48L2k+CiAgICAgICAgICAgICAgICA8c3Bhbj5aUHJvbXB0"
    "PC9zcGFuPgogICAgICAgICAgICA8L2E+CiAgICAgICAgICAgIDxkaXYgY2xhc3M9ImZsZXgtMSBm"
    "bGV4IGl0ZW1zLWNlbnRlciBqdXN0aWZ5LWVuZCBnYXAtMyI+CiAgICAgICAgICAgICAgICA8YnV0"
    "dG9uIGlkPSJ0aGVtZS10b2dnbGUiIGNsYXNzPSJpbmxpbmUtZmxleCBpdGVtcy1jZW50ZXIganVz"
    "dGlmeS1jZW50ZXIgcm91bmRlZC1tZCBib3JkZXIgYm9yZGVyLWJvcmRlciBiZy1iYWNrZ3JvdW5k"
    "IHAtMiB0ZXh0LW11dGVkLWZvcmVncm91bmQgdHJhbnNpdGlvbi1jb2xvcnMgaG92ZXI6YmctYWNj"
    "ZW50IGhvdmVyOnRleHQtYWNjZW50LWZvcmVncm91bmQgY3Vyc29yLXBvaW50ZXIiPgogICAgICAg"
    "ICAgICAgICAgICAgIDxpIGRhdGEtbHVjaWRlPSJzdW4iIGlkPSJ0aGVtZS1pY29uLXN1biIgY2xh"
    "c3M9ImgtNCB3LTQiPjwvaT4KICAgICAgICAgICAgICAgICAgICA8aSBkYXRhLWx1Y2lkZT0ibW9v"
    "biIgaWQ9InRoZW1lLWljb24tbW9vbiIgY2xhc3M9ImgtNCB3LTQgaGlkZGVuIj48L2k+CiAgICAg"
    "ICAgICAgICAgICA8L2J1dHRvbj4KICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgPC9kaXY+CiAg"
    "ICA8L2hlYWRlcj4KCiAgICA8bWFpbiBjbGFzcz0ibXgtYXV0byBtYXgtdy00eGwgcHgtNCBweS04"
    "IHNtOnB4LTYgc206cHktMTIiPgoKICAgICAgICA8c2VjdGlvbiBjbGFzcz0ibWItMTAgdGV4dC1j"
    "ZW50ZXIiPgogICAgICAgICAgICA8aDEgY2xhc3M9InRleHQtM3hsIGZvbnQtYm9sZCB0cmFja2lu"
    "Zy10aWdodCBzbTp0ZXh0LTR4bCI+CiAgICAgICAgICAgICAgICBHZW5lcmEgcHJvbXB0cyBlc3Ry"
    "dWN0dXJhZG9zCiAgICAgICAgICAgICAgICA8c3BhbiBjbGFzcz0idGV4dC1wcmltYXJ5Ij5wYXJh"
    "IEdMTTwvc3Bhbj4KICAgICAgICAgICAgPC9oMT4KICAgICAgICAgICAgPHAgY2xhc3M9Im10LTMg"
    "dGV4dC1tdXRlZC1mb3JlZ3JvdW5kIj4KICAgICAgICAgICAgICAgIERlc2NyaWJlIHR1IHByb3ll"
    "Y3RvIHkgb2J0aWVuZSBwcm9tcHRzIG9wdGltaXphZG9zIHBhcmEgZGVzYXJyb2xsbyBkZSBzb2Z0"
    "d2FyZS4KICAgICAgICAgICAgPC9wPgogICAgICAgIDwvc2VjdGlvbj4KCiAgICAgICAgPHNlY3Rp"
    "b24gY2xhc3M9InNwYWNlLXktNiI+CgogICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAg"
    "PGRpdiBjbGFzcz0iZ3JpZCBncmlkLWNvbHMtNCBnYXAtMiI+CiAgICAgICAgICAgICAgICAgICAg"
    "PGJ1dHRvbiBkYXRhLXR5cGU9InN5c3RlbSIgY2xhc3M9InByb21wdC10eXBlLWNhcmQgZmxleCBp"
    "dGVtcy1jZW50ZXIganVzdGlmeS1jZW50ZXIgZ2FwLTIgcm91bmRlZC1sZyBib3JkZXIgYm9yZGVy"
    "LWJvcmRlciBiZy1jYXJkIHB4LTMgcHktMiB0cmFuc2l0aW9uLWFsbCBob3Zlcjpib3JkZXItcmlu"
    "ZyBob3ZlcjpzaGFkb3ctc20gY3Vyc29yLXBvaW50ZXIiPgogICAgICAgICAgICAgICAgICAgICAg"
    "ICA8aSBkYXRhLWx1Y2lkZT0ibW9uaXRvciIgY2xhc3M9ImgtNCB3LTQiPjwvaT4KICAgICAgICAg"
    "ICAgICAgICAgICAgICAgPHNwYW4gY2xhc3M9InRleHQteHMgZm9udC1tZWRpdW0gdGV4dC1jYXJk"
    "LWZvcmVncm91bmQiPlN5c3RlbTwvc3Bhbj4KICAgICAgICAgICAgICAgICAgICA8L2J1dHRvbj4K"
    "ICAgICAgICAgICAgICAgICAgICA8YnV0dG9uIGRhdGEtdHlwZT0ic3RhcnQiIGNsYXNzPSJwcm9t"
    "cHQtdHlwZS1jYXJkIGZsZXggaXRlbXMtY2VudGVyIGp1c3RpZnktY2VudGVyIGdhcC0yIHJvdW5k"
    "ZWQtbGcgYm9yZGVyIGJvcmRlci1ib3JkZXIgYmctY2FyZCBweC0zIHB5LTIgdHJhbnNpdGlvbi1h"
    "bGwgaG92ZXI6Ym9yZGVyLXJpbmcgaG92ZXI6c2hhZG93LXNtIGN1cnNvci1wb2ludGVyIj4KICAg"
    "ICAgICAgICAgICAgICAgICAgICAgPGkgZGF0YS1sdWNpZGU9InJvY2tldCIgY2xhc3M9ImgtNCB3"
    "LTQiPjwvaT4KICAgICAgICAgICAgICAgICAgICAgICAgPHNwYW4gY2xhc3M9InRleHQteHMgZm9u"
    "dC1tZWRpdW0gdGV4dC1jYXJkLWZvcmVncm91bmQiPlN0YXJ0PC9zcGFuPgogICAgICAgICAgICAg"
    "ICAgICAgIDwvYnV0dG9uPgogICAgICAgICAgICAgICAgICAgIDxidXR0b24gZGF0YS10eXBlPSJm"
    "b2xsb3d1cCIgY2xhc3M9InByb21wdC10eXBlLWNhcmQgZmxleCBpdGVtcy1jZW50ZXIganVzdGlm"
    "eS1jZW50ZXIgZ2FwLTIgcm91bmRlZC1sZyBib3JkZXIgYm9yZGVyLWJvcmRlciBiZy1jYXJkIHB4"
    "LTMgcHktMiB0cmFuc2l0aW9uLWFsbCBob3Zlcjpib3JkZXItcmluZyBob3ZlcjpzaGFkb3ctc20g"
    "Y3Vyc29yLXBvaW50ZXIiPgogICAgICAgICAgICAgICAgICAgICAgICA8aSBkYXRhLWx1Y2lkZT0i"
    "cmVwZWF0IiBjbGFzcz0iaC00IHctNCI+PC9pPgogICAgICAgICAgICAgICAgICAgICAgICA8c3Bh"
    "biBjbGFzcz0idGV4dC14cyBmb250LW1lZGl1bSB0ZXh0LWNhcmQtZm9yZWdyb3VuZCI+Rm9sbG93"
    "LVVwPC9zcGFuPgogICAgICAgICAgICAgICAgICAgIDwvYnV0dG9uPgogICAgICAgICAgICAgICAg"
    "ICAgIDxidXR0b24gZGF0YS10eXBlPSJkZWJ1ZyIgY2xhc3M9InByb21wdC10eXBlLWNhcmQgZmxl"
    "eCBpdGVtcy1jZW50ZXIganVzdGlmeS1jZW50ZXIgZ2FwLTIgcm91bmRlZC1sZyBib3JkZXIgYm9y"
    "ZGVyLWJvcmRlciBiZy1jYXJkIHB4LTMgcHktMiB0cmFuc2l0aW9uLWFsbCBob3Zlcjpib3JkZXIt"
    "cmluZyBob3ZlcjpzaGFkb3ctc20gY3Vyc29yLXBvaW50ZXIiPgogICAgICAgICAgICAgICAgICAg"
    "ICAgICA8aSBkYXRhLWx1Y2lkZT0iYnVnIiBjbGFzcz0iaC00IHctNCI+PC9pPgogICAgICAgICAg"
    "ICAgICAgICAgICAgICA8c3BhbiBjbGFzcz0idGV4dC14cyBmb250LW1lZGl1bSB0ZXh0LWNhcmQt"
    "Zm9yZWdyb3VuZCI+RGVidWc8L3NwYW4+CiAgICAgICAgICAgICAgICAgICAgPC9idXR0b24+CiAg"
    "ICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgPC9kaXY+CgogICAgICAgICAgICA8ZGl2"
    "PgogICAgICAgICAgICAgICAgPGxhYmVsIGZvcj0idXNlci1pbnB1dCIgY2xhc3M9Im1iLTIgYmxv"
    "Y2sgdGV4dC1zbSBmb250LW1lZGl1bSB0ZXh0LWNlbnRlciI+RGVzY3JpYmUgdHUgcHJveWVjdG8g"
    "byB0YXJlYTwvbGFiZWw+CiAgICAgICAgICAgICAgICA8dGV4dGFyZWEKICAgICAgICAgICAgICAg"
    "ICAgICBpZD0idXNlci1pbnB1dCIKICAgICAgICAgICAgICAgICAgICByb3dzPSI0IgogICAgICAg"
    "ICAgICAgICAgICAgIGNsYXNzPSJmbGV4IHctZnVsbCByb3VuZGVkLWxnIGJvcmRlciBib3JkZXIt"
    "aW5wdXQgYmctYmFja2dyb3VuZCBweC0zIHB5LTIuNSB0ZXh0LXNtIHNoYWRvdy14cyB0cmFuc2l0"
    "aW9uLWNvbG9ycyBwbGFjZWhvbGRlcjp0ZXh0LW11dGVkLWZvcmVncm91bmQgZm9jdXMtdmlzaWJs"
    "ZTpvdXRsaW5lLW5vbmUgZm9jdXMtdmlzaWJsZTpyaW5nLTIgZm9jdXMtdmlzaWJsZTpyaW5nLXJp"
    "bmcgcmVzaXplLW5vbmUiCiAgICAgICAgICAgICAgICAgICAgcGxhY2Vob2xkZXI9IkVqZW1wbG86"
    "IENyZWFyIHVuYSBBUEkgUkVTVCBjb24gUHl0aG9uIHkgRmFzdEFQSSBwYXJhIGdlc3Rpb24gZGUg"
    "dGFyZWFzLCBjb24gYXV0ZW50aWNhY2lvbiBKV1QgeSBiYXNlIGRlIGRhdG9zIFBvc3RncmVTUUwu"
    "Li4iCiAgICAgICAgICAgICAgICA+PC90ZXh0YXJlYT4KICAgICAgICAgICAgPC9kaXY+CgogICAg"
    "ICAgICAgICA8ZGl2IGNsYXNzPSJncmlkIGdyaWQtY29scy0xIGdhcC00IHNtOmdyaWQtY29scy0y"
    "Ij4KICAgICAgICAgICAgICAgIDxkaXY+CiAgICAgICAgICAgICAgICAgICAgPGxhYmVsIGZvcj0i"
    "bGFuZ3VhZ2Utc2VsZWN0IiBjbGFzcz0ibWItMiBibG9jayB0ZXh0LXNtIGZvbnQtbWVkaXVtIHRl"
    "eHQtbXV0ZWQtZm9yZWdyb3VuZCI+TGVuZ3VhamUgKG9wY2lvbmFsKTwvbGFiZWw+CiAgICAgICAg"
    "ICAgICAgICAgICAgPHNlbGVjdCBpZD0ibGFuZ3VhZ2Utc2VsZWN0IiBjbGFzcz0iZmxleCBoLTkg"
    "dy1mdWxsIHJvdW5kZWQtbGcgYm9yZGVyIGJvcmRlci1pbnB1dCBiZy1iYWNrZ3JvdW5kIHB4LTMg"
    "dGV4dC1zbSBzaGFkb3cteHMgdHJhbnNpdGlvbi1jb2xvcnMgZm9jdXMtdmlzaWJsZTpvdXRsaW5l"
    "LW5vbmUgZm9jdXMtdmlzaWJsZTpyaW5nLTIgZm9jdXMtdmlzaWJsZTpyaW5nLXJpbmciPgogICAg"
    "ICAgICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVlPSIiPkF1dG8tZGV0ZWN0YXI8L29wdGlv"
    "bj4KICAgICAgICAgICAgICAgICAgICAgICAgPG9wdGlvbiB2YWx1ZT0iUHl0aG9uIj5QeXRob248"
    "L29wdGlvbj4KICAgICAgICAgICAgICAgICAgICAgICAgPG9wdGlvbiB2YWx1ZT0iVHlwZVNjcmlw"
    "dCI+VHlwZVNjcmlwdDwvb3B0aW9uPgogICAgICAgICAgICAgICAgICAgICAgICA8b3B0aW9uIHZh"
    "bHVlPSJEYXJ0Ij5EYXJ0PC9vcHRpb24+CiAgICAgICAgICAgICAgICAgICAgICAgIDxvcHRpb24g"
    "dmFsdWU9IkphdmFTY3JpcHQiPkphdmFTY3JpcHQ8L29wdGlvbj4KICAgICAgICAgICAgICAgICAg"
    "ICAgICAgPG9wdGlvbiB2YWx1ZT0iUnVzdCI+UnVzdDwvb3B0aW9uPgogICAgICAgICAgICAgICAg"
    "ICAgICAgICA8b3B0aW9uIHZhbHVlPSJHbyI+R288L29wdGlvbj4KICAgICAgICAgICAgICAgICAg"
    "ICAgICAgPG9wdGlvbiB2YWx1ZT0iSmF2YSI+SmF2YTwvb3B0aW9uPgogICAgICAgICAgICAgICAg"
    "ICAgICAgICA8b3B0aW9uIHZhbHVlPSJDIyI+QyM8L29wdGlvbj4KICAgICAgICAgICAgICAgICAg"
    "ICAgICAgPG9wdGlvbiB2YWx1ZT0iUEhQIj5QSFA8L29wdGlvbj4KICAgICAgICAgICAgICAgICAg"
    "ICAgICAgPG9wdGlvbiB2YWx1ZT0iUnVieSI+UnVieTwvb3B0aW9uPgogICAgICAgICAgICAgICAg"
    "ICAgICAgICA8b3B0aW9uIHZhbHVlPSJTd2lmdCI+U3dpZnQ8L29wdGlvbj4KICAgICAgICAgICAg"
    "ICAgICAgICAgICAgPG9wdGlvbiB2YWx1ZT0iS290bGluIj5Lb3RsaW48L29wdGlvbj4KICAgICAg"
    "ICAgICAgICAgICAgICA8L3NlbGVjdD4KICAgICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAg"
    "ICAgICAgPGRpdj4KICAgICAgICAgICAgICAgICAgICA8bGFiZWwgZm9yPSJmcmFtZXdvcmstc2Vs"
    "ZWN0IiBjbGFzcz0ibWItMiBibG9jayB0ZXh0LXNtIGZvbnQtbWVkaXVtIHRleHQtbXV0ZWQtZm9y"
    "ZWdyb3VuZCI+RnJhbWV3b3JrIChvcGNpb25hbCk8L2xhYmVsPgogICAgICAgICAgICAgICAgICAg"
    "IDxzZWxlY3QgaWQ9ImZyYW1ld29yay1zZWxlY3QiIGNsYXNzPSJmbGV4IGgtOSB3LWZ1bGwgcm91"
    "bmRlZC1sZyBib3JkZXIgYm9yZGVyLWlucHV0IGJnLWJhY2tncm91bmQgcHgtMyB0ZXh0LXNtIHNo"
    "YWRvdy14cyB0cmFuc2l0aW9uLWNvbG9ycyBmb2N1cy12aXNpYmxlOm91dGxpbmUtbm9uZSBmb2N1"
    "cy12aXNpYmxlOnJpbmctMiBmb2N1cy12aXNpYmxlOnJpbmctcmluZyI+CiAgICAgICAgICAgICAg"
    "ICAgICAgICAgIDxvcHRpb24gdmFsdWU9IiI+TmluZ3VubyAvIEF1dG88L29wdGlvbj4KICAgICAg"
    "ICAgICAgICAgICAgICAgICAgPG9wdGlvbiB2YWx1ZT0iRmFzdEFQSSI+RmFzdEFQSTwvb3B0aW9u"
    "PgogICAgICAgICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVlPSJEamFuZ28iPkRqYW5nbzwv"
    "b3B0aW9uPgogICAgICAgICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVlPSJGbHV0dGVyIj5G"
    "bHV0dGVyPC9vcHRpb24+CiAgICAgICAgICAgICAgICAgICAgICAgIDxvcHRpb24gdmFsdWU9IkZs"
    "YXNrIj5GbGFzazwvb3B0aW9uPgogICAgICAgICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVl"
    "PSJOZXh0LmpzIj5OZXh0LmpzPC9vcHRpb24+CiAgICAgICAgICAgICAgICAgICAgICAgIDxvcHRp"
    "b24gdmFsdWU9IlJlYWN0Ij5SZWFjdDwvb3B0aW9uPgogICAgICAgICAgICAgICAgICAgICAgICA8"
    "b3B0aW9uIHZhbHVlPSJWdWUuanMiPlZ1ZS5qczwvb3B0aW9uPgogICAgICAgICAgICAgICAgICAg"
    "ICAgICA8b3B0aW9uIHZhbHVlPSJFeHByZXNzIj5FeHByZXNzPC9vcHRpb24+CiAgICAgICAgICAg"
    "ICAgICAgICAgICAgIDxvcHRpb24gdmFsdWU9Ik5lc3RKUyI+TmVzdEpTPC9vcHRpb24+CiAgICAg"
    "ICAgICAgICAgICAgICAgICAgIDxvcHRpb24gdmFsdWU9IlNwcmluZyBCb290Ij5TcHJpbmcgQm9v"
    "dDwvb3B0aW9uPgogICAgICAgICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVlPSJBY3RpeCI+"
    "QWN0aXg8L29wdGlvbj4KICAgICAgICAgICAgICAgICAgICAgICAgPG9wdGlvbiB2YWx1ZT0iQXh1"
    "bSI+QXh1bTwvb3B0aW9uPgogICAgICAgICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVlPSJM"
    "YXJhdmVsIj5MYXJhdmVsPC9vcHRpb24+CiAgICAgICAgICAgICAgICAgICAgICAgIDxvcHRpb24g"
    "dmFsdWU9IlJhaWxzIj5SYWlsczwvb3B0aW9uPgogICAgICAgICAgICAgICAgICAgIDwvc2VsZWN0"
    "PgogICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgIDwvZGl2PgoKICAgICAgICAgICAg"
    "PGJ1dHRvbgogICAgICAgICAgICAgICAgaWQ9ImdlbmVyYXRlLWJ0biIKICAgICAgICAgICAgICAg"
    "IGNsYXNzPSJpbmxpbmUtZmxleCB3LWZ1bGwgaXRlbXMtY2VudGVyIGp1c3RpZnktY2VudGVyIGdh"
    "cC0yIHJvdW5kZWQtbGcgYmctcHJpbWFyeSBweC00IHB5LTIuNSB0ZXh0LXNtIGZvbnQtbWVkaXVt"
    "IHRleHQtcHJpbWFyeS1mb3JlZ3JvdW5kIHNoYWRvdy14cyB0cmFuc2l0aW9uLWNvbG9ycyBob3Zl"
    "cjpiZy1wcmltYXJ5LzkwIGRpc2FibGVkOnBvaW50ZXItZXZlbnRzLW5vbmUgZGlzYWJsZWQ6b3Bh"
    "Y2l0eS01MCBjdXJzb3ItcG9pbnRlciIKICAgICAgICAgICAgICAgIGRpc2FibGVkCiAgICAgICAg"
    "ICAgID4KICAgICAgICAgICAgICAgIDxpIGRhdGEtbHVjaWRlPSJ6YXAiIGNsYXNzPSJoLTQgdy00"
    "Ij48L2k+CiAgICAgICAgICAgICAgICA8c3BhbiBpZD0iYnRuLXRleHQiPkdlbmVyYXIgUHJvbXB0"
    "PC9zcGFuPgogICAgICAgICAgICAgICAgPHNwYW4gaWQ9ImJ0bi1zcGlubmVyIiBjbGFzcz0iaGlk"
    "ZGVuIj4KICAgICAgICAgICAgICAgICAgICA8c3ZnIGNsYXNzPSJoLTQgdy00IGFuaW1hdGUtc3Bp"
    "biIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIj48Y2lyY2xlIGNsYXNzPSJvcGFjaXR5"
    "LTI1IiBjeD0iMTIiIGN5PSIxMiIgcj0iMTAiIHN0cm9rZT0iY3VycmVudENvbG9yIiBzdHJva2Ut"
    "d2lkdGg9IjQiPjwvY2lyY2xlPjxwYXRoIGNsYXNzPSJvcGFjaXR5LTc1IiBmaWxsPSJjdXJyZW50"
    "Q29sb3IiIGQ9Ik00IDEyYTggOCAwIDAxOC04VjBDNS4zNzMgMCAwIDUuMzczIDAgMTJoNHoiPjwv"
    "cGF0aD48L3N2Zz4KICAgICAgICAgICAgICAgIDwvc3Bhbj4KICAgICAgICAgICAgPC9idXR0b24+"
    "CgogICAgICAgIDwvc2VjdGlvbj4KCiAgICAgICAgPHNlY3Rpb24gaWQ9ImVycm9yLXNlY3Rpb24i"
    "IGNsYXNzPSJtdC02IGhpZGRlbiI+CiAgICAgICAgICAgIDxkaXYgY2xhc3M9InJvdW5kZWQtbGcg"
    "Ym9yZGVyIGJvcmRlci1kZXN0cnVjdGl2ZS81MCBiZy1kZXN0cnVjdGl2ZS8xMCBwLTQgdGV4dC1z"
    "bSB0ZXh0LWRlc3RydWN0aXZlIj4KICAgICAgICAgICAgICAgIDxwIGlkPSJlcnJvci1tZXNzYWdl"
    "Ij48L3A+CiAgICAgICAgICAgIDwvZGl2PgogICAgICAgIDwvc2VjdGlvbj4KCiAgICAgICAgPHNl"
    "Y3Rpb24gaWQ9InJlc3VsdC1zZWN0aW9uIiBjbGFzcz0ibXQtOCBoaWRkZW4iPgogICAgICAgICAg"
    "ICA8ZGl2IGNsYXNzPSJyb3VuZGVkLWxnIGJvcmRlciBib3JkZXItYm9yZGVyIGJnLWNhcmQgc2hh"
    "ZG93LXNtIj4KICAgICAgICAgICAgICAgIDxkaXYgY2xhc3M9ImZsZXggaXRlbXMtY2VudGVyIGp1"
    "c3RpZnktYmV0d2VlbiBib3JkZXItYiBib3JkZXItYm9yZGVyIHB4LTQgcHktMyI+CiAgICAgICAg"
    "ICAgICAgICAgICAgPGRpdiBjbGFzcz0iZmxleCBpdGVtcy1jZW50ZXIgZ2FwLTIiPgogICAgICAg"
    "ICAgICAgICAgICAgICAgICA8c3BhbiBpZD0icmVzdWx0LWljb24iPjwvc3Bhbj4KICAgICAgICAg"
    "ICAgICAgICAgICAgICAgPGgyIGlkPSJyZXN1bHQtdGl0bGUiIGNsYXNzPSJ0ZXh0LXNtIGZvbnQt"
    "c2VtaWJvbGQgdGV4dC1jYXJkLWZvcmVncm91bmQiPjwvaDI+CiAgICAgICAgICAgICAgICAgICAg"
    "PC9kaXY+CiAgICAgICAgICAgICAgICAgICAgPGRpdiBjbGFzcz0iZmxleCBpdGVtcy1jZW50ZXIg"
    "Z2FwLTIiPgogICAgICAgICAgICAgICAgICAgICAgICA8YnV0dG9uIGlkPSJjb3B5LWJ0biIgY2xh"
    "c3M9ImlubGluZS1mbGV4IGl0ZW1zLWNlbnRlciBnYXAtMS41IHJvdW5kZWQtbWQgYm9yZGVyIGJv"
    "cmRlci1ib3JkZXIgYmctYmFja2dyb3VuZCBweC0yLjUgcHktMS41IHRleHQteHMgZm9udC1tZWRp"
    "dW0gdGV4dC1tdXRlZC1mb3JlZ3JvdW5kIHRyYW5zaXRpb24tY29sb3JzIGhvdmVyOmJnLWFjY2Vu"
    "dCBob3Zlcjp0ZXh0LWFjY2VudC1mb3JlZ3JvdW5kIGN1cnNvci1wb2ludGVyIj4KICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgIDxpIGRhdGEtbHVjaWRlPSJjb3B5IiBjbGFzcz0iaC0zLjUgdy0z"
    "LjUiPjwvaT4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIENvcGlhcgogICAgICAgICAgICAg"
    "ICAgICAgICAgICA8L2J1dHRvbj4KICAgICAgICAgICAgICAgICAgICAgICAgPGJ1dHRvbiBpZD0i"
    "cmVnZW5lcmF0ZS1idG4iIGNsYXNzPSJpbmxpbmUtZmxleCBpdGVtcy1jZW50ZXIgZ2FwLTEuNSBy"
    "b3VuZGVkLW1kIGJvcmRlciBib3JkZXItYm9yZGVyIGJnLWJhY2tncm91bmQgcHgtMi41IHB5LTEu"
    "NSB0ZXh0LXhzIGZvbnQtbWVkaXVtIHRleHQtbXV0ZWQtZm9yZWdyb3VuZCB0cmFuc2l0aW9uLWNv"
    "bG9ycyBob3ZlcjpiZy1hY2NlbnQgaG92ZXI6dGV4dC1hY2NlbnQtZm9yZWdyb3VuZCBjdXJzb3It"
    "cG9pbnRlciI+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8aSBkYXRhLWx1Y2lkZT0icmVm"
    "cmVzaC1jdyIgY2xhc3M9ImgtMy41IHctMy41Ij48L2k+CiAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICBSZWdlbmVyYXIKICAgICAgICAgICAgICAgICAgICAgICAgPC9idXR0b24+CiAgICAgICAg"
    "ICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgICAg"
    "IDxkaXYgY2xhc3M9InAtNCI+CiAgICAgICAgICAgICAgICAgICAgPHByZSBpZD0icmVzdWx0LWNv"
    "bnRlbnQiIGNsYXNzPSJ3aGl0ZXNwYWNlLXByZS13cmFwIGJyZWFrLXdvcmRzIGZvbnQtbW9ubyB0"
    "ZXh0LXNtIGxlYWRpbmctcmVsYXhlZCB0ZXh0LWNhcmQtZm9yZWdyb3VuZCI+PC9wcmU+CiAgICAg"
    "ICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgICAgIDxkaXYgY2xhc3M9ImJvcmRlci10IGJv"
    "cmRlci1ib3JkZXIgcHgtNCBweS0yIj4KICAgICAgICAgICAgICAgICAgICA8cCBpZD0icmVzdWx0"
    "LXRpbWVzdGFtcCIgY2xhc3M9InRleHQteHMgdGV4dC1tdXRlZC1mb3JlZ3JvdW5kIj48L3A+CiAg"
    "ICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgPC9zZWN0aW9u"
    "PgoKICAgIDwvbWFpbj4KCiAgICA8Zm9vdGVyIGNsYXNzPSJib3JkZXItdCBib3JkZXItYm9yZGVy"
    "IHB5LTYgdGV4dC1jZW50ZXIgdGV4dC14cyB0ZXh0LW11dGVkLWZvcmVncm91bmQiPgogICAgICAg"
    "IDxwPlpQcm9tcHQgJm1kYXNoOyBHZW5lcmFkb3IgZGUgcHJvbXB0cyBlc3RydWN0dXJhZG9zIHBh"
    "cmEgR0xNPC9wPgogICAgPC9mb290ZXI+CgogICAgPHNjcmlwdCBzcmM9Ii9qcy9hcHAuanMiPjwv"
    "c2NyaXB0Pgo8L2JvZHk+CjwvaHRtbD4K"
)



INDEX_HTML = base64.b64decode(_INDEX_B64).decode("utf-8")

load_dotenv()

app = FastAPI(
    title="ZPrompt",
    description="Generador de prompts estructurados para desarrollo de software",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


class PromptRequest(BaseModel):
    text: str = Field(..., min_length=5, max_length=5000)
    prompt_type: str = Field(..., pattern="^(system|start|followup|debug)$")
    language: str | None = None
    framework: str | None = None


class PromptResponse(BaseModel):
    prompt: str
    prompt_type: str
    label: str
    timestamp: str


@app.get("/")
def serve_index():
    return HTMLResponse(content=INDEX_HTML)


@app.get("/api/health")
def health_check():
    return {"status": "ok", "timestamp": datetime.now(timezone.utc).isoformat()}


@app.get("/api/templates")
def get_templates():
    result = []
    for key, label in TEMPLATE_LABELS.items():
        result.append(
            {
                "id": key,
                "label": label,
                "description": TEMPLATE_DESCRIPTIONS.get(key, ""),
            }
        )
    return {"templates": result}


@app.post("/api/generate", response_model=PromptResponse)
async def create_prompt(request: PromptRequest):
    if not os.environ.get("OPENAI_API_KEY"):
        raise HTTPException(
            status_code=500,
            detail="OPENAI_API_KEY no configurada. Agregala como variable de entorno.",
        )

    try:
        prompt_text = await generate_prompt(
            text=request.text,
            prompt_type=request.prompt_type,
            language=request.language,
            framework=request.framework,
        )
        return PromptResponse(
            prompt=prompt_text,
            prompt_type=request.prompt_type,
            label=TEMPLATE_LABELS.get(request.prompt_type, ""),
            timestamp=datetime.now(timezone.utc).isoformat(),
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        raise HTTPException(
            status_code=500, detail=f"Error generando prompt: {str(e)}"
        )


@app.get("/api/data")
def get_sample_data():
    return {
        "data": [
            {"id": 1, "name": "Sample Item 1", "value": 100},
            {"id": 2, "name": "Sample Item 2", "value": 200},
            {"id": 3, "name": "Sample Item 3", "value": 300},
        ],
        "total": 3,
        "timestamp": "2024-01-01T00:00:00Z",
    }

_INDEX_B64 = (
    "PCFET0NUWVBFIGh0bWw+CjxodG1sIGxhbmc9ImVzIiBjbGFzcz0iZGFyayI+CjxoZWFkPgogICAg"
    "PG1ldGEgY2hhcnNldD0iVVRGLTgiPgogICAgPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9"
    "IndpZHRoPWRldmljZS13aWR0aCwgaW5pdGlhbC1zY2FsZT0xLjAiPgogICAgPHRpdGxlPlpQcm9t"
    "cHQgLSBHZW5lcmFkb3IgZGUgUHJvbXB0cyBwYXJhIERlc2Fycm9sbG8gZGUgU29mdHdhcmU8L3Rp"
    "dGxlPgogICAgPG1ldGEgbmFtZT0iZGVzY3JpcHRpb24iIGNvbnRlbnQ9IkdlbmVyYSBwcm9tcHRz"
    "IGVzdHJ1Y3R1cmFkb3MgcGFyYSBHTE0gb3B0aW1pemFkb3MgcGFyYSBkZXNhcnJvbGxvIGRlIHNv"
    "ZnR3YXJlLiI+CiAgICA8bGluayByZWw9Imljb24iIHR5cGU9ImltYWdlL3gtaWNvbiIgaHJlZj0i"
    "L2Zhdmljb24uaWNvIj4KICAgIDxsaW5rIHJlbD0ic3R5bGVzaGVldCIgaHJlZj0iL2Nzcy9zdHls"
    "ZXMuY3NzIj4KICAgIDxzY3JpcHQgc3JjPSJodHRwczovL3VucGtnLmNvbS9sdWNpZGVAbGF0ZXN0"
    "Ij48L3NjcmlwdD4KPC9oZWFkPgo8Ym9keSBjbGFzcz0ibWluLWgtc2NyZWVuIGJnLWJhY2tncm91"
    "bmQgdGV4dC1mb3JlZ3JvdW5kIGZvbnQtc2FucyBhbnRpYWxpYXNlZCI+CgogICAgPGhlYWRlciBj"
    "bGFzcz0ic3RpY2t5IHRvcC0wIHotNTAgdy1mdWxsIGJvcmRlci1iIGJvcmRlci1ib3JkZXIgYmct"
    "YmFja2dyb3VuZC84MCBiYWNrZHJvcC1ibHVyLXNtIj4KICAgICAgICA8ZGl2IGNsYXNzPSJteC1h"
    "dXRvIGZsZXggaC0xNCBtYXgtdy00eGwgaXRlbXMtY2VudGVyIHB4LTQgc206cHgtNiI+CiAgICAg"
    "ICAgICAgIDxkaXYgY2xhc3M9ImZsZXgtMSI+PC9kaXY+CiAgICAgICAgICAgIDxhIGhyZWY9Ii8i"
    "IGNsYXNzPSJmbGV4IGl0ZW1zLWNlbnRlciBnYXAtMiB0ZXh0LWxnIGZvbnQtc2VtaWJvbGQgdHJh"
    "Y2tpbmctdGlnaHQiPgogICAgICAgICAgICAgICAgPGkgZGF0YS1sdWNpZGU9InphcCIgY2xhc3M9"
    "ImgtNSB3LTUgdGV4dC1wcmltYXJ5Ij48L2k+CiAgICAgICAgICAgICAgICA8c3Bhbj5aUHJvbXB0"
    "PC9zcGFuPgogICAgICAgICAgICA8L2E+CiAgICAgICAgICAgIDxkaXYgY2xhc3M9ImZsZXgtMSBm"
    "bGV4IGl0ZW1zLWNlbnRlciBqdXN0aWZ5LWVuZCBnYXAtMyI+CiAgICAgICAgICAgICAgICA8YnV0"
    "dG9uIGlkPSJ0aGVtZS10b2dnbGUiIGNsYXNzPSJpbmxpbmUtZmxleCBpdGVtcy1jZW50ZXIganVz"
    "dGlmeS1jZW50ZXIgcm91bmRlZC1tZCBib3JkZXIgYm9yZGVyLWJvcmRlciBiZy1iYWNrZ3JvdW5k"
    "IHAtMiB0ZXh0LW11dGVkLWZvcmVncm91bmQgdHJhbnNpdGlvbi1jb2xvcnMgaG92ZXI6YmctYWNj"
    "ZW50IGhvdmVyOnRleHQtYWNjZW50LWZvcmVncm91bmQgY3Vyc29yLXBvaW50ZXIiPgogICAgICAg"
    "ICAgICAgICAgICAgIDxpIGRhdGEtbHVjaWRlPSJzdW4iIGlkPSJ0aGVtZS1pY29uLXN1biIgY2xh"
    "c3M9ImgtNCB3LTQiPjwvaT4KICAgICAgICAgICAgICAgICAgICA8aSBkYXRhLWx1Y2lkZT0ibW9v"
    "biIgaWQ9InRoZW1lLWljb24tbW9vbiIgY2xhc3M9ImgtNCB3LTQgaGlkZGVuIj48L2k+CiAgICAg"
    "ICAgICAgICAgICA8L2J1dHRvbj4KICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgPC9kaXY+CiAg"
    "ICA8L2hlYWRlcj4KCiAgICA8bWFpbiBjbGFzcz0ibXgtYXV0byBtYXgtdy00eGwgcHgtNCBweS04"
    "IHNtOnB4LTYgc206cHktMTIiPgoKICAgICAgICA8c2VjdGlvbiBjbGFzcz0ibWItMTAgdGV4dC1j"
    "ZW50ZXIiPgogICAgICAgICAgICA8aDEgY2xhc3M9InRleHQtM3hsIGZvbnQtYm9sZCB0cmFja2lu"
    "Zy10aWdodCBzbTp0ZXh0LTR4bCI+CiAgICAgICAgICAgICAgICBHZW5lcmEgcHJvbXB0cyBlc3Ry"
    "dWN0dXJhZG9zCiAgICAgICAgICAgICAgICA8c3BhbiBjbGFzcz0idGV4dC1wcmltYXJ5Ij5wYXJh"
    "IEdMTTwvc3Bhbj4KICAgICAgICAgICAgPC9oMT4KICAgICAgICAgICAgPHAgY2xhc3M9Im10LTMg"
    "dGV4dC1tdXRlZC1mb3JlZ3JvdW5kIj4KICAgICAgICAgICAgICAgIERlc2NyaWJlIHR1IHByb3ll"
    "Y3RvIHkgb2J0aWVuZSBwcm9tcHRzIG9wdGltaXphZG9zIHBhcmEgZGVzYXJyb2xsbyBkZSBzb2Z0"
    "d2FyZS4KICAgICAgICAgICAgPC9wPgogICAgICAgIDwvc2VjdGlvbj4KCiAgICAgICAgPHNlY3Rp"
    "b24gY2xhc3M9InNwYWNlLXktNiI+CgogICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAg"
    "PGRpdiBjbGFzcz0iZ3JpZCBncmlkLWNvbHMtNCBnYXAtMiI+CiAgICAgICAgICAgICAgICAgICAg"
    "PGJ1dHRvbiBkYXRhLXR5cGU9InN5c3RlbSIgY2xhc3M9InByb21wdC10eXBlLWNhcmQgZmxleCBp"
    "dGVtcy1jZW50ZXIganVzdGlmeS1jZW50ZXIgZ2FwLTIgcm91bmRlZC1sZyBib3JkZXIgYm9yZGVy"
    "LWJvcmRlciBiZy1jYXJkIHB4LTMgcHktMiB0cmFuc2l0aW9uLWFsbCBob3Zlcjpib3JkZXItcmlu"
    "ZyBob3ZlcjpzaGFkb3ctc20gY3Vyc29yLXBvaW50ZXIiPgogICAgICAgICAgICAgICAgICAgICAg"
    "ICA8aSBkYXRhLWx1Y2lkZT0ibW9uaXRvciIgY2xhc3M9ImgtNCB3LTQiPjwvaT4KICAgICAgICAg"
    "ICAgICAgICAgICAgICAgPHNwYW4gY2xhc3M9InRleHQteHMgZm9udC1tZWRpdW0gdGV4dC1jYXJk"
    "LWZvcmVncm91bmQiPlN5c3RlbTwvc3Bhbj4KICAgICAgICAgICAgICAgICAgICA8L2J1dHRvbj4K"
    "ICAgICAgICAgICAgICAgICAgICA8YnV0dG9uIGRhdGEtdHlwZT0ic3RhcnQiIGNsYXNzPSJwcm9t"
    "cHQtdHlwZS1jYXJkIGZsZXggaXRlbXMtY2VudGVyIGp1c3RpZnktY2VudGVyIGdhcC0yIHJvdW5k"
    "ZWQtbGcgYm9yZGVyIGJvcmRlci1ib3JkZXIgYmctY2FyZCBweC0zIHB5LTIgdHJhbnNpdGlvbi1h"
    "bGwgaG92ZXI6Ym9yZGVyLXJpbmcgaG92ZXI6c2hhZG93LXNtIGN1cnNvci1wb2ludGVyIj4KICAg"
    "ICAgICAgICAgICAgICAgICAgICAgPGkgZGF0YS1sdWNpZGU9InJvY2tldCIgY2xhc3M9ImgtNCB3"
    "LTQiPjwvaT4KICAgICAgICAgICAgICAgICAgICAgICAgPHNwYW4gY2xhc3M9InRleHQteHMgZm9u"
    "dC1tZWRpdW0gdGV4dC1jYXJkLWZvcmVncm91bmQiPlN0YXJ0PC9zcGFuPgogICAgICAgICAgICAg"
    "ICAgICAgIDwvYnV0dG9uPgogICAgICAgICAgICAgICAgICAgIDxidXR0b24gZGF0YS10eXBlPSJm"
    "b2xsb3d1cCIgY2xhc3M9InByb21wdC10eXBlLWNhcmQgZmxleCBpdGVtcy1jZW50ZXIganVzdGlm"
    "eS1jZW50ZXIgZ2FwLTIgcm91bmRlZC1sZyBib3JkZXIgYm9yZGVyLWJvcmRlciBiZy1jYXJkIHB4"
    "LTMgcHktMiB0cmFuc2l0aW9uLWFsbCBob3Zlcjpib3JkZXItcmluZyBob3ZlcjpzaGFkb3ctc20g"
    "Y3Vyc29yLXBvaW50ZXIiPgogICAgICAgICAgICAgICAgICAgICAgICA8aSBkYXRhLWx1Y2lkZT0i"
    "cmVwZWF0IiBjbGFzcz0iaC00IHctNCI+PC9pPgogICAgICAgICAgICAgICAgICAgICAgICA8c3Bh"
    "biBjbGFzcz0idGV4dC14cyBmb250LW1lZGl1bSB0ZXh0LWNhcmQtZm9yZWdyb3VuZCI+Rm9sbG93"
    "LVVwPC9zcGFuPgogICAgICAgICAgICAgICAgICAgIDwvYnV0dG9uPgogICAgICAgICAgICAgICAg"
    "ICAgIDxidXR0b24gZGF0YS10eXBlPSJkZWJ1ZyIgY2xhc3M9InByb21wdC10eXBlLWNhcmQgZmxl"
    "eCBpdGVtcy1jZW50ZXIganVzdGlmeS1jZW50ZXIgZ2FwLTIgcm91bmRlZC1sZyBib3JkZXIgYm9y"
    "ZGVyLWJvcmRlciBiZy1jYXJkIHB4LTMgcHktMiB0cmFuc2l0aW9uLWFsbCBob3Zlcjpib3JkZXIt"
    "cmluZyBob3ZlcjpzaGFkb3ctc20gY3Vyc29yLXBvaW50ZXIiPgogICAgICAgICAgICAgICAgICAg"
    "ICAgICA8aSBkYXRhLWx1Y2lkZT0iYnVnIiBjbGFzcz0iaC00IHctNCI+PC9pPgogICAgICAgICAg"
    "ICAgICAgICAgICAgICA8c3BhbiBjbGFzcz0idGV4dC14cyBmb250LW1lZGl1bSB0ZXh0LWNhcmQt"
    "Zm9yZWdyb3VuZCI+RGVidWc8L3NwYW4+CiAgICAgICAgICAgICAgICAgICAgPC9idXR0b24+CiAg"
    "ICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgPC9kaXY+CgogICAgICAgICAgICA8ZGl2"
    "PgogICAgICAgICAgICAgICAgPGxhYmVsIGZvcj0idXNlci1pbnB1dCIgY2xhc3M9Im1iLTIgYmxv"
    "Y2sgdGV4dC1zbSBmb250LW1lZGl1bSB0ZXh0LWNlbnRlciI+RGVzY3JpYmUgdHUgcHJveWVjdG8g"
    "byB0YXJlYTwvbGFiZWw+CiAgICAgICAgICAgICAgICA8dGV4dGFyZWEKICAgICAgICAgICAgICAg"
    "ICAgICBpZD0idXNlci1pbnB1dCIKICAgICAgICAgICAgICAgICAgICByb3dzPSI0IgogICAgICAg"
    "ICAgICAgICAgICAgIGNsYXNzPSJmbGV4IHctZnVsbCByb3VuZGVkLWxnIGJvcmRlciBib3JkZXIt"
    "aW5wdXQgYmctYmFja2dyb3VuZCBweC0zIHB5LTIuNSB0ZXh0LXNtIHNoYWRvdy14cyB0cmFuc2l0"
    "aW9uLWNvbG9ycyBwbGFjZWhvbGRlcjp0ZXh0LW11dGVkLWZvcmVncm91bmQgZm9jdXMtdmlzaWJs"
    "ZTpvdXRsaW5lLW5vbmUgZm9jdXMtdmlzaWJsZTpyaW5nLTIgZm9jdXMtdmlzaWJsZTpyaW5nLXJp"
    "bmcgcmVzaXplLW5vbmUiCiAgICAgICAgICAgICAgICAgICAgcGxhY2Vob2xkZXI9IkVqZW1wbG86"
    "IENyZWFyIHVuYSBBUEkgUkVTVCBjb24gUHl0aG9uIHkgRmFzdEFQSSBwYXJhIGdlc3Rpb24gZGUg"
    "dGFyZWFzLCBjb24gYXV0ZW50aWNhY2lvbiBKV1QgeSBiYXNlIGRlIGRhdG9zIFBvc3RncmVTUUwu"
    "Li4iCiAgICAgICAgICAgICAgICA+PC90ZXh0YXJlYT4KICAgICAgICAgICAgPC9kaXY+CgogICAg"
    "ICAgICAgICA8ZGl2IGNsYXNzPSJncmlkIGdyaWQtY29scy0xIGdhcC00IHNtOmdyaWQtY29scy0y"
    "Ij4KICAgICAgICAgICAgICAgIDxkaXY+CiAgICAgICAgICAgICAgICAgICAgPGxhYmVsIGZvcj0i"
    "bGFuZ3VhZ2Utc2VsZWN0IiBjbGFzcz0ibWItMiBibG9jayB0ZXh0LXNtIGZvbnQtbWVkaXVtIHRl"
    "eHQtbXV0ZWQtZm9yZWdyb3VuZCI+TGVuZ3VhamUgKG9wY2lvbmFsKTwvbGFiZWw+CiAgICAgICAg"
    "ICAgICAgICAgICAgPHNlbGVjdCBpZD0ibGFuZ3VhZ2Utc2VsZWN0IiBjbGFzcz0iZmxleCBoLTkg"
    "dy1mdWxsIHJvdW5kZWQtbGcgYm9yZGVyIGJvcmRlci1pbnB1dCBiZy1iYWNrZ3JvdW5kIHB4LTMg"
    "dGV4dC1zbSBzaGFkb3cteHMgdHJhbnNpdGlvbi1jb2xvcnMgZm9jdXMtdmlzaWJsZTpvdXRsaW5l"
    "LW5vbmUgZm9jdXMtdmlzaWJsZTpyaW5nLTIgZm9jdXMtdmlzaWJsZTpyaW5nLXJpbmciPgogICAg"
    "ICAgICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVlPSIiPkF1dG8tZGV0ZWN0YXI8L29wdGlv"
    "bj4KICAgICAgICAgICAgICAgICAgICAgICAgPG9wdGlvbiB2YWx1ZT0iUHl0aG9uIj5QeXRob248"
    "L29wdGlvbj4KICAgICAgICAgICAgICAgICAgICAgICAgPG9wdGlvbiB2YWx1ZT0iVHlwZVNjcmlw"
    "dCI+VHlwZVNjcmlwdDwvb3B0aW9uPgogICAgICAgICAgICAgICAgICAgICAgICA8b3B0aW9uIHZh"
    "bHVlPSJEYXJ0Ij5EYXJ0PC9vcHRpb24+CiAgICAgICAgICAgICAgICAgICAgICAgIDxvcHRpb24g"
    "dmFsdWU9IkphdmFTY3JpcHQiPkphdmFTY3JpcHQ8L29wdGlvbj4KICAgICAgICAgICAgICAgICAg"
    "ICAgICAgPG9wdGlvbiB2YWx1ZT0iUnVzdCI+UnVzdDwvb3B0aW9uPgogICAgICAgICAgICAgICAg"
    "ICAgICAgICA8b3B0aW9uIHZhbHVlPSJHbyI+R288L29wdGlvbj4KICAgICAgICAgICAgICAgICAg"
    "ICAgICAgPG9wdGlvbiB2YWx1ZT0iSmF2YSI+SmF2YTwvb3B0aW9uPgogICAgICAgICAgICAgICAg"
    "ICAgICAgICA8b3B0aW9uIHZhbHVlPSJDIyI+QyM8L29wdGlvbj4KICAgICAgICAgICAgICAgICAg"
    "ICAgICAgPG9wdGlvbiB2YWx1ZT0iUEhQIj5QSFA8L29wdGlvbj4KICAgICAgICAgICAgICAgICAg"
    "ICAgICAgPG9wdGlvbiB2YWx1ZT0iUnVieSI+UnVieTwvb3B0aW9uPgogICAgICAgICAgICAgICAg"
    "ICAgICAgICA8b3B0aW9uIHZhbHVlPSJTd2lmdCI+U3dpZnQ8L29wdGlvbj4KICAgICAgICAgICAg"
    "ICAgICAgICAgICAgPG9wdGlvbiB2YWx1ZT0iS290bGluIj5Lb3RsaW48L29wdGlvbj4KICAgICAg"
    "ICAgICAgICAgICAgICA8L3NlbGVjdD4KICAgICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAg"
    "ICAgICAgPGRpdj4KICAgICAgICAgICAgICAgICAgICA8bGFiZWwgZm9yPSJmcmFtZXdvcmstc2Vs"
    "ZWN0IiBjbGFzcz0ibWItMiBibG9jayB0ZXh0LXNtIGZvbnQtbWVkaXVtIHRleHQtbXV0ZWQtZm9y"
    "ZWdyb3VuZCI+RnJhbWV3b3JrIChvcGNpb25hbCk8L2xhYmVsPgogICAgICAgICAgICAgICAgICAg"
    "IDxzZWxlY3QgaWQ9ImZyYW1ld29yay1zZWxlY3QiIGNsYXNzPSJmbGV4IGgtOSB3LWZ1bGwgcm91"
    "bmRlZC1sZyBib3JkZXIgYm9yZGVyLWlucHV0IGJnLWJhY2tncm91bmQgcHgtMyB0ZXh0LXNtIHNo"
    "YWRvdy14cyB0cmFuc2l0aW9uLWNvbG9ycyBmb2N1cy12aXNpYmxlOm91dGxpbmUtbm9uZSBmb2N1"
    "cy12aXNpYmxlOnJpbmctMiBmb2N1cy12aXNpYmxlOnJpbmctcmluZyI+CiAgICAgICAgICAgICAg"
    "ICAgICAgICAgIDxvcHRpb24gdmFsdWU9IiI+TmluZ3VubyAvIEF1dG88L29wdGlvbj4KICAgICAg"
    "ICAgICAgICAgICAgICAgICAgPG9wdGlvbiB2YWx1ZT0iRmFzdEFQSSI+RmFzdEFQSTwvb3B0aW9u"
    "PgogICAgICAgICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVlPSJEamFuZ28iPkRqYW5nbzwv"
    "b3B0aW9uPgogICAgICAgICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVlPSJGbHV0dGVyIj5G"
    "bHV0dGVyPC9vcHRpb24+CiAgICAgICAgICAgICAgICAgICAgICAgIDxvcHRpb24gdmFsdWU9IkZs"
    "YXNrIj5GbGFzazwvb3B0aW9uPgogICAgICAgICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVl"
    "PSJOZXh0LmpzIj5OZXh0LmpzPC9vcHRpb24+CiAgICAgICAgICAgICAgICAgICAgICAgIDxvcHRp"
    "b24gdmFsdWU9IlJlYWN0Ij5SZWFjdDwvb3B0aW9uPgogICAgICAgICAgICAgICAgICAgICAgICA8"
    "b3B0aW9uIHZhbHVlPSJWdWUuanMiPlZ1ZS5qczwvb3B0aW9uPgogICAgICAgICAgICAgICAgICAg"
    "ICAgICA8b3B0aW9uIHZhbHVlPSJFeHByZXNzIj5FeHByZXNzPC9vcHRpb24+CiAgICAgICAgICAg"
    "ICAgICAgICAgICAgIDxvcHRpb24gdmFsdWU9Ik5lc3RKUyI+TmVzdEpTPC9vcHRpb24+CiAgICAg"
    "ICAgICAgICAgICAgICAgICAgIDxvcHRpb24gdmFsdWU9IlNwcmluZyBCb290Ij5TcHJpbmcgQm9v"
    "dDwvb3B0aW9uPgogICAgICAgICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVlPSJBY3RpeCI+"
    "QWN0aXg8L29wdGlvbj4KICAgICAgICAgICAgICAgICAgICAgICAgPG9wdGlvbiB2YWx1ZT0iQXh1"
    "bSI+QXh1bTwvb3B0aW9uPgogICAgICAgICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVlPSJM"
    "YXJhdmVsIj5MYXJhdmVsPC9vcHRpb24+CiAgICAgICAgICAgICAgICAgICAgICAgIDxvcHRpb24g"
    "dmFsdWU9IlJhaWxzIj5SYWlsczwvb3B0aW9uPgogICAgICAgICAgICAgICAgICAgIDwvc2VsZWN0"
    "PgogICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgIDwvZGl2PgoKICAgICAgICAgICAg"
    "PGJ1dHRvbgogICAgICAgICAgICAgICAgaWQ9ImdlbmVyYXRlLWJ0biIKICAgICAgICAgICAgICAg"
    "IGNsYXNzPSJpbmxpbmUtZmxleCB3LWZ1bGwgaXRlbXMtY2VudGVyIGp1c3RpZnktY2VudGVyIGdh"
    "cC0yIHJvdW5kZWQtbGcgYmctcHJpbWFyeSBweC00IHB5LTIuNSB0ZXh0LXNtIGZvbnQtbWVkaXVt"
    "IHRleHQtcHJpbWFyeS1mb3JlZ3JvdW5kIHNoYWRvdy14cyB0cmFuc2l0aW9uLWNvbG9ycyBob3Zl"
    "cjpiZy1wcmltYXJ5LzkwIGRpc2FibGVkOnBvaW50ZXItZXZlbnRzLW5vbmUgZGlzYWJsZWQ6b3Bh"
    "Y2l0eS01MCBjdXJzb3ItcG9pbnRlciIKICAgICAgICAgICAgICAgIGRpc2FibGVkCiAgICAgICAg"
    "ICAgID4KICAgICAgICAgICAgICAgIDxpIGRhdGEtbHVjaWRlPSJ6YXAiIGNsYXNzPSJoLTQgdy00"
    "Ij48L2k+CiAgICAgICAgICAgICAgICA8c3BhbiBpZD0iYnRuLXRleHQiPkdlbmVyYXIgUHJvbXB0"
    "PC9zcGFuPgogICAgICAgICAgICAgICAgPHNwYW4gaWQ9ImJ0bi1zcGlubmVyIiBjbGFzcz0iaGlk"
    "ZGVuIj4KICAgICAgICAgICAgICAgICAgICA8c3ZnIGNsYXNzPSJoLTQgdy00IGFuaW1hdGUtc3Bp"
    "biIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIj48Y2lyY2xlIGNsYXNzPSJvcGFjaXR5"
    "LTI1IiBjeD0iMTIiIGN5PSIxMiIgcj0iMTAiIHN0cm9rZT0iY3VycmVudENvbG9yIiBzdHJva2Ut"
    "d2lkdGg9IjQiPjwvY2lyY2xlPjxwYXRoIGNsYXNzPSJvcGFjaXR5LTc1IiBmaWxsPSJjdXJyZW50"
    "Q29sb3IiIGQ9Ik00IDEyYTggOCAwIDAxOC04VjBDNS4zNzMgMCAwIDUuMzczIDAgMTJoNHoiPjwv"
    "cGF0aD48L3N2Zz4KICAgICAgICAgICAgICAgIDwvc3Bhbj4KICAgICAgICAgICAgPC9idXR0b24+"
    "CgogICAgICAgIDwvc2VjdGlvbj4KCiAgICAgICAgPHNlY3Rpb24gaWQ9ImVycm9yLXNlY3Rpb24i"
    "IGNsYXNzPSJtdC02IGhpZGRlbiI+CiAgICAgICAgICAgIDxkaXYgY2xhc3M9InJvdW5kZWQtbGcg"
    "Ym9yZGVyIGJvcmRlci1kZXN0cnVjdGl2ZS81MCBiZy1kZXN0cnVjdGl2ZS8xMCBwLTQgdGV4dC1z"
    "bSB0ZXh0LWRlc3RydWN0aXZlIj4KICAgICAgICAgICAgICAgIDxwIGlkPSJlcnJvci1tZXNzYWdl"
    "Ij48L3A+CiAgICAgICAgICAgIDwvZGl2PgogICAgICAgIDwvc2VjdGlvbj4KCiAgICAgICAgPHNl"
    "Y3Rpb24gaWQ9InJlc3VsdC1zZWN0aW9uIiBjbGFzcz0ibXQtOCBoaWRkZW4iPgogICAgICAgICAg"
    "ICA8ZGl2IGNsYXNzPSJyb3VuZGVkLWxnIGJvcmRlciBib3JkZXItYm9yZGVyIGJnLWNhcmQgc2hh"
    "ZG93LXNtIj4KICAgICAgICAgICAgICAgIDxkaXYgY2xhc3M9ImZsZXggaXRlbXMtY2VudGVyIGp1"
    "c3RpZnktYmV0d2VlbiBib3JkZXItYiBib3JkZXItYm9yZGVyIHB4LTQgcHktMyI+CiAgICAgICAg"
    "ICAgICAgICAgICAgPGRpdiBjbGFzcz0iZmxleCBpdGVtcy1jZW50ZXIgZ2FwLTIiPgogICAgICAg"
    "ICAgICAgICAgICAgICAgICA8c3BhbiBpZD0icmVzdWx0LWljb24iPjwvc3Bhbj4KICAgICAgICAg"
    "ICAgICAgICAgICAgICAgPGgyIGlkPSJyZXN1bHQtdGl0bGUiIGNsYXNzPSJ0ZXh0LXNtIGZvbnQt"
    "c2VtaWJvbGQgdGV4dC1jYXJkLWZvcmVncm91bmQiPjwvaDI+CiAgICAgICAgICAgICAgICAgICAg"
    "PC9kaXY+CiAgICAgICAgICAgICAgICAgICAgPGRpdiBjbGFzcz0iZmxleCBpdGVtcy1jZW50ZXIg"
    "Z2FwLTIiPgogICAgICAgICAgICAgICAgICAgICAgICA8YnV0dG9uIGlkPSJjb3B5LWJ0biIgY2xh"
    "c3M9ImlubGluZS1mbGV4IGl0ZW1zLWNlbnRlciBnYXAtMS41IHJvdW5kZWQtbWQgYm9yZGVyIGJv"
    "cmRlci1ib3JkZXIgYmctYmFja2dyb3VuZCBweC0yLjUgcHktMS41IHRleHQteHMgZm9udC1tZWRp"
    "dW0gdGV4dC1tdXRlZC1mb3JlZ3JvdW5kIHRyYW5zaXRpb24tY29sb3JzIGhvdmVyOmJnLWFjY2Vu"
    "dCBob3Zlcjp0ZXh0LWFjY2VudC1mb3JlZ3JvdW5kIGN1cnNvci1wb2ludGVyIj4KICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgIDxpIGRhdGEtbHVjaWRlPSJjb3B5IiBjbGFzcz0iaC0zLjUgdy0z"
    "LjUiPjwvaT4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIENvcGlhcgogICAgICAgICAgICAg"
    "ICAgICAgICAgICA8L2J1dHRvbj4KICAgICAgICAgICAgICAgICAgICAgICAgPGJ1dHRvbiBpZD0i"
    "cmVnZW5lcmF0ZS1idG4iIGNsYXNzPSJpbmxpbmUtZmxleCBpdGVtcy1jZW50ZXIgZ2FwLTEuNSBy"
    "b3VuZGVkLW1kIGJvcmRlciBib3JkZXItYm9yZGVyIGJnLWJhY2tncm91bmQgcHgtMi41IHB5LTEu"
    "NSB0ZXh0LXhzIGZvbnQtbWVkaXVtIHRleHQtbXV0ZWQtZm9yZWdyb3VuZCB0cmFuc2l0aW9uLWNv"
    "bG9ycyBob3ZlcjpiZy1hY2NlbnQgaG92ZXI6dGV4dC1hY2NlbnQtZm9yZWdyb3VuZCBjdXJzb3It"
    "cG9pbnRlciI+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8aSBkYXRhLWx1Y2lkZT0icmVm"
    "cmVzaC1jdyIgY2xhc3M9ImgtMy41IHctMy41Ij48L2k+CiAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICBSZWdlbmVyYXIKICAgICAgICAgICAgICAgICAgICAgICAgPC9idXR0b24+CiAgICAgICAg"
    "ICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgICAg"
    "IDxkaXYgY2xhc3M9InAtNCI+CiAgICAgICAgICAgICAgICAgICAgPHByZSBpZD0icmVzdWx0LWNv"
    "bnRlbnQiIGNsYXNzPSJ3aGl0ZXNwYWNlLXByZS13cmFwIGJyZWFrLXdvcmRzIGZvbnQtbW9ubyB0"
    "ZXh0LXNtIGxlYWRpbmctcmVsYXhlZCB0ZXh0LWNhcmQtZm9yZWdyb3VuZCI+PC9wcmU+CiAgICAg"
    "ICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgICAgIDxkaXYgY2xhc3M9ImJvcmRlci10IGJv"
    "cmRlci1ib3JkZXIgcHgtNCBweS0yIj4KICAgICAgICAgICAgICAgICAgICA8cCBpZD0icmVzdWx0"
    "LXRpbWVzdGFtcCIgY2xhc3M9InRleHQteHMgdGV4dC1tdXRlZC1mb3JlZ3JvdW5kIj48L3A+CiAg"
    "ICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgPC9zZWN0aW9u"
    "PgoKICAgIDwvbWFpbj4KCiAgICA8Zm9vdGVyIGNsYXNzPSJib3JkZXItdCBib3JkZXItYm9yZGVy"
    "IHB5LTYgdGV4dC1jZW50ZXIgdGV4dC14cyB0ZXh0LW11dGVkLWZvcmVncm91bmQiPgogICAgICAg"
    "IDxwPlpQcm9tcHQgJm1kYXNoOyBHZW5lcmFkb3IgZGUgcHJvbXB0cyBlc3RydWN0dXJhZG9zIHBh"
    "cmEgR0xNPC9wPgogICAgPC9mb290ZXI+CgogICAgPHNjcmlwdCBzcmM9Ii9qcy9hcHAuanMiPjwv"
    "c2NyaXB0Pgo8L2JvZHk+CjwvaHRtbD4K"
)



INDEX_HTML = base64.b64decode(_INDEX_B64).decode("utf-8")

load_dotenv()

app = FastAPI(
    title="ZPrompt",
    description="Generador de prompts estructurados para desarrollo de software",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


class PromptRequest(BaseModel):
    text: str = Field(..., min_length=5, max_length=5000)
    prompt_type: str = Field(..., pattern="^(system|start|followup|debug)$")
    language: str | None = None
    framework: str | None = None


class PromptResponse(BaseModel):
    prompt: str
    prompt_type: str
    label: str
    timestamp: str


@app.get("/")
def serve_index():
    return HTMLResponse(content=INDEX_HTML)


@app.get("/api/health")
def health_check():
    return {"status": "ok", "timestamp": datetime.now(timezone.utc).isoformat()}


@app.get("/api/templates")
def get_templates():
    result = []
    for key, label in TEMPLATE_LABELS.items():
        result.append(
            {
                "id": key,
                "label": label,
                "description": TEMPLATE_DESCRIPTIONS.get(key, ""),
            }
        )
    return {"templates": result}


@app.post("/api/generate", response_model=PromptResponse)
async def create_prompt(request: PromptRequest):
    if not os.environ.get("OPENAI_API_KEY"):
        raise HTTPException(
            status_code=500,
            detail="OPENAI_API_KEY no configurada. Agregala como variable de entorno.",
        )

    try:
        prompt_text = await generate_prompt(
            text=request.text,
            prompt_type=request.prompt_type,
            language=request.language,
            framework=request.framework,
        )
        return PromptResponse(
            prompt=prompt_text,
            prompt_type=request.prompt_type,
            label=TEMPLATE_LABELS.get(request.prompt_type, ""),
            timestamp=datetime.now(timezone.utc).isoformat(),
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        raise HTTPException(
            status_code=500, detail=f"Error generando prompt: {str(e)}"
        )


@app.get("/api/data")
def get_sample_data():
    return {
        "data": [
            {"id": 1, "name": "Sample Item 1", "value": 100},
            {"id": 2, "name": "Sample Item 2", "value": 200},
            {"id": 3, "name": "Sample Item 3", "value": 300},
        ],
        "total": 3,
        "timestamp": "2024-01-01T00:00:00Z",
    }
